//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class BluetoothConnectionAccessAdapter : global::java.lang.Object, global::com.intel.bluetooth.BluetoothConnectionAccess {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_shutdown0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_encrypt1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isClosed2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getRemoteAddress3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getRemoteDevice4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setRemoteDevice5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSecurityOpt6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getBluetoothStack7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_markAuthenticated8;
        
        protected BluetoothConnectionAccessAdapter(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass = @__class;
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_shutdown0 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "shutdown", "()V");
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_encrypt1 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "encrypt", "(JZ)Z");
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_isClosed2 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "isClosed", "()Z");
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_getRemoteAddress3 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "getRemoteAddress", "()J");
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_getRemoteDevice4 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "getRemoteDevice", "()Ljavax/bluetooth/RemoteDevice;");
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_setRemoteDevice5 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "setRemoteDevice", "(Ljavax/bluetooth/RemoteDevice;)V");
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_getSecurityOpt6 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "getSecurityOpt", "()I");
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_getBluetoothStack7 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "getBluetoothStack", "()Lcom/intel/bluetooth/BluetoothStack;");
            global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_markAuthenticated8 = @__env.GetMethodID(global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.staticClass, "markAuthenticated", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void shutdown() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_shutdown0);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(JZ)Z")]
        public virtual bool encrypt(long par0, bool par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_encrypt1, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool isClosed() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_isClosed2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        public virtual long getRemoteAddress() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_getRemoteAddress3)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/bluetooth/RemoteDevice;")]
        public virtual global::javax.bluetooth.RemoteDevice getRemoteDevice() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.RemoteDevice>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_getRemoteDevice4));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/RemoteDevice;)V")]
        public virtual void setRemoteDevice(global::javax.bluetooth.RemoteDevice par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_setRemoteDevice5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getSecurityOpt() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_getSecurityOpt6)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/intel/bluetooth/BluetoothStack;")]
        public virtual global::com.intel.bluetooth.BluetoothStack getBluetoothStack() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothStack>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_getBluetoothStack7));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void markAuthenticated() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.BluetoothConnectionAccessAdapter.j4n_markAuthenticated8);
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.BluetoothConnectionAccessAdapter(@__env);
            }
        }
    }
    #endregion
}
