//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface BluetoothStackExtension {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(J)I")]
        int readRemoteDeviceRSSI(long par0);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class BluetoothStackExtension_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.@__BluetoothStackExtension.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::com.intel.bluetooth.BluetoothStackExtension), typeof(global::com.intel.bluetooth.BluetoothStackExtension_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::com.intel.bluetooth.BluetoothStackExtension), typeof(global::com.intel.bluetooth.BluetoothStackExtension_))]
    internal sealed partial class @__BluetoothStackExtension : global::java.lang.Object, global::com.intel.bluetooth.BluetoothStackExtension {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_readRemoteDeviceRSSI0;
        
        private @__BluetoothStackExtension(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.@__BluetoothStackExtension.staticClass = @__class;
            global::com.intel.bluetooth.@__BluetoothStackExtension.j4n_readRemoteDeviceRSSI0 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothStackExtension.staticClass, "readRemoteDeviceRSSI", "(J)I");
        }
        
        public int readRemoteDeviceRSSI(long par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::com.intel.bluetooth.@__BluetoothStackExtension.j4n_readRemoteDeviceRSSI0, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0))));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__BluetoothStackExtension);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "readRemoteDeviceRSSI", "readRemoteDeviceRSSI0", "(J)I"));
            return methods;
        }
        
        private static int readRemoteDeviceRSSI0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, long par0) {
            // (J)I
            // (J)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::com.intel.bluetooth.BluetoothStackExtension @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothStackExtension>(@__env, @__obj);
            @__return = ((int)(@__real.readRemoteDeviceRSSI(par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.@__BluetoothStackExtension(@__env);
            }
        }
    }
    #endregion
}
