//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface BluetoothConnectionAccess {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        void shutdown();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(JZ)Z")]
        bool encrypt(long par0, bool par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        bool isClosed();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getRemoteAddress();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/bluetooth/RemoteDevice;")]
        global::javax.bluetooth.RemoteDevice getRemoteDevice();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/RemoteDevice;)V")]
        void setRemoteDevice(global::javax.bluetooth.RemoteDevice par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        int getSecurityOpt();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/intel/bluetooth/BluetoothStack;")]
        global::com.intel.bluetooth.BluetoothStack getBluetoothStack();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        void markAuthenticated();
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class BluetoothConnectionAccess_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::com.intel.bluetooth.BluetoothConnectionAccess), typeof(global::com.intel.bluetooth.BluetoothConnectionAccess_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::com.intel.bluetooth.BluetoothConnectionAccess), typeof(global::com.intel.bluetooth.BluetoothConnectionAccess_))]
    internal sealed partial class @__BluetoothConnectionAccess : global::java.lang.Object, global::com.intel.bluetooth.BluetoothConnectionAccess {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_shutdown0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_encrypt1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isClosed2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getRemoteAddress3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getRemoteDevice4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setRemoteDevice5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSecurityOpt6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getBluetoothStack7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_markAuthenticated8;
        
        private @__BluetoothConnectionAccess(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass = @__class;
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_shutdown0 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "shutdown", "()V");
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_encrypt1 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "encrypt", "(JZ)Z");
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_isClosed2 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "isClosed", "()Z");
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_getRemoteAddress3 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "getRemoteAddress", "()J");
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_getRemoteDevice4 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "getRemoteDevice", "()Ljavax/bluetooth/RemoteDevice;");
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_setRemoteDevice5 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "setRemoteDevice", "(Ljavax/bluetooth/RemoteDevice;)V");
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_getSecurityOpt6 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "getSecurityOpt", "()I");
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_getBluetoothStack7 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "getBluetoothStack", "()Lcom/intel/bluetooth/BluetoothStack;");
            global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_markAuthenticated8 = @__env.GetMethodID(global::com.intel.bluetooth.@__BluetoothConnectionAccess.staticClass, "markAuthenticated", "()V");
        }
        
        public void shutdown() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_shutdown0);
            }
        }
        
        public bool encrypt(long par0, bool par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_encrypt1, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1))));
            }
        }
        
        public bool isClosed() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_isClosed2)));
            }
        }
        
        public long getRemoteAddress() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_getRemoteAddress3)));
            }
        }
        
        public global::javax.bluetooth.RemoteDevice getRemoteDevice() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.RemoteDevice>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_getRemoteDevice4));
            }
        }
        
        public void setRemoteDevice(global::javax.bluetooth.RemoteDevice par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_setRemoteDevice5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        public int getSecurityOpt() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_getSecurityOpt6)));
            }
        }
        
        public global::com.intel.bluetooth.BluetoothStack getBluetoothStack() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothStack>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_getBluetoothStack7));
            }
        }
        
        public void markAuthenticated() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.@__BluetoothConnectionAccess.j4n_markAuthenticated8);
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__BluetoothConnectionAccess);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "shutdown", "shutdown0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "encrypt", "encrypt1", "(JZ)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isClosed", "isClosed2", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getRemoteAddress", "getRemoteAddress3", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getRemoteDevice", "getRemoteDevice4", "()Ljavax/bluetooth/RemoteDevice;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setRemoteDevice", "setRemoteDevice5", "(Ljavax/bluetooth/RemoteDevice;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getSecurityOpt", "getSecurityOpt6", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getBluetoothStack", "getBluetoothStack7", "()Lcom/intel/bluetooth/BluetoothStack;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "markAuthenticated", "markAuthenticated8", "()V"));
            return methods;
        }
        
        private static void shutdown0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__real.shutdown();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool encrypt1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, long par0, bool par1) {
            // (JZ)Z
            // (JZ)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__return = ((bool)(@__real.encrypt(par0, par1)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool isClosed2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__return = ((bool)(@__real.isClosed()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getRemoteAddress3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__return = ((long)(@__real.getRemoteAddress()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getRemoteDevice4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljavax/bluetooth/RemoteDevice;
            // ()Ljavax/bluetooth/RemoteDevice;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getRemoteDevice());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setRemoteDevice5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljavax/bluetooth/RemoteDevice;)V
            // (Ljavax/bluetooth/RemoteDevice;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__real.setRemoteDevice(global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.RemoteDevice>(@__env, par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int getSecurityOpt6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__return = ((int)(@__real.getSecurityOpt()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getBluetoothStack7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lcom/intel/bluetooth/BluetoothStack;
            // ()Lcom/intel/bluetooth/BluetoothStack;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::com.intel.bluetooth.BluetoothStack>(@__env, @__real.getBluetoothStack());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void markAuthenticated8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::com.intel.bluetooth.BluetoothConnectionAccess @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothConnectionAccess>(@__env, @__obj);
            @__real.markAuthenticated();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.@__BluetoothConnectionAccess(@__env);
            }
        }
    }
    #endregion
}
