//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class BluetoothConsts : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_toString0;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_SHORT_UUID_BASE1;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROTOCOL_SCHEME_L2CAP2;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROTOCOL_SCHEME_RFCOMM3;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROTOCOL_SCHEME_BT_OBEX4;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROTOCOL_SCHEME_TCP_OBEX5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_L2CAP_PROTOCOL_UUID6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_RFCOMM_PROTOCOL_UUID7;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_OBEX_PROTOCOL_UUID8;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_OBEXFileTransferServiceClass_UUID9;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_RFCOMM_CHANNEL_MIN10;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_RFCOMM_CHANNEL_MAX11;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_L2CAP_PSM_MIN12;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_L2CAP_PSM_MIN_JSR_8213;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_L2CAP_PSM_MAX14;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_TCP_OBEX_DEFAULT_PORT15;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_API_VERSION16;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_OBEX_API_VERSION17;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_MASTER_SWITCH18;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_SD_ATTR_RETRIEVABLE_MAX19;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_CONNECTED_DEVICES_MAX20;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_L2CAP_RECEIVEMTU_MAX21;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_SD_TRANS_MAX22;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_CONNECTED_INQUIRY_SCAN23;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_CONNECTED_PAGE_SCAN24;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_CONNECTED_INQUIRY25;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUETOOTH_CONNECTED_PAGE26;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_SERIAL_PORT_UUID27;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_BluetoothProfileDescriptorList28;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_BrowseGroupList29;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ClientExecutableURL30;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DocumentationURL31;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_IconURL32;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_LanguageBasedAttributeIDList33;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ProtocolDescriptorList34;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ProviderName35;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceAvailability36;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceClassIDList37;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceDatabaseState38;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceDescription39;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceID40;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceInfoTimeToLive41;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_AttributeIDServiceName42;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceName43;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceRecordHandle44;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_ServiceRecordState45;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_VersionNumberList46;
        
        protected BluetoothConsts(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.BluetoothConsts.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String SHORT_UUID_BASE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_SHORT_UUID_BASE1));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROTOCOL_SCHEME_L2CAP {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROTOCOL_SCHEME_L2CAP2));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROTOCOL_SCHEME_RFCOMM {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROTOCOL_SCHEME_RFCOMM3));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROTOCOL_SCHEME_BT_OBEX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROTOCOL_SCHEME_BT_OBEX4));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROTOCOL_SCHEME_TCP_OBEX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROTOCOL_SCHEME_TCP_OBEX5));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljavax/bluetooth/UUID;")]
        public static global::javax.bluetooth.UUID L2CAP_PROTOCOL_UUID {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.UUID>(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_L2CAP_PROTOCOL_UUID6));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljavax/bluetooth/UUID;")]
        public static global::javax.bluetooth.UUID RFCOMM_PROTOCOL_UUID {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.UUID>(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_RFCOMM_PROTOCOL_UUID7));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljavax/bluetooth/UUID;")]
        public static global::javax.bluetooth.UUID OBEX_PROTOCOL_UUID {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.UUID>(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_OBEX_PROTOCOL_UUID8));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljavax/bluetooth/UUID;")]
        public static global::javax.bluetooth.UUID OBEXFileTransferServiceClass_UUID {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.UUID>(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_OBEXFileTransferServiceClass_UUID9));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int RFCOMM_CHANNEL_MIN {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_RFCOMM_CHANNEL_MIN10)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int RFCOMM_CHANNEL_MAX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_RFCOMM_CHANNEL_MAX11)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int L2CAP_PSM_MIN {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_L2CAP_PSM_MIN12)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int L2CAP_PSM_MIN_JSR_82 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_L2CAP_PSM_MIN_JSR_8213)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int L2CAP_PSM_MAX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_L2CAP_PSM_MAX14)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int TCP_OBEX_DEFAULT_PORT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_TCP_OBEX_DEFAULT_PORT15)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_API_VERSION {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_API_VERSION16));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_OBEX_API_VERSION {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_OBEX_API_VERSION17));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_MASTER_SWITCH {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_MASTER_SWITCH18));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_SD_ATTR_RETRIEVABLE_MAX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_SD_ATTR_RETRIEVABLE_MAX19));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_CONNECTED_DEVICES_MAX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_DEVICES_MAX20));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_L2CAP_RECEIVEMTU_MAX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_L2CAP_RECEIVEMTU_MAX21));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_SD_TRANS_MAX {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_SD_TRANS_MAX22));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_CONNECTED_INQUIRY_SCAN {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_INQUIRY_SCAN23));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_CONNECTED_PAGE_SCAN {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_PAGE_SCAN24));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_CONNECTED_INQUIRY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_INQUIRY25));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUETOOTH_CONNECTED_PAGE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_PAGE26));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljavax/bluetooth/UUID;")]
        public static global::javax.bluetooth.UUID SERIAL_PORT_UUID {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.UUID>(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_SERIAL_PORT_UUID27));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int BluetoothProfileDescriptorList {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_BluetoothProfileDescriptorList28)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int BrowseGroupList {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_BrowseGroupList29)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ClientExecutableURL {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ClientExecutableURL30)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int DocumentationURL {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_DocumentationURL31)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int IconURL {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_IconURL32)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int LanguageBasedAttributeIDList {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_LanguageBasedAttributeIDList33)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ProtocolDescriptorList {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ProtocolDescriptorList34)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ProviderName {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ProviderName35)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceAvailability {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceAvailability36)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceClassIDList {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceClassIDList37)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceDatabaseState {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceDatabaseState38)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceDescription {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceDescription39)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceID {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceID40)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceInfoTimeToLive {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceInfoTimeToLive41)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int AttributeIDServiceName {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_AttributeIDServiceName42)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceName {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceName43)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceRecordHandle {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceRecordHandle44)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int ServiceRecordState {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceRecordState45)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int VersionNumberList {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_VersionNumberList46)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.BluetoothConsts.staticClass = @__class;
            global::com.intel.bluetooth.BluetoothConsts.j4n_toString0 = @__env.GetStaticMethodID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "toString", "(Ljavax/bluetooth/DeviceClass;)Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_SHORT_UUID_BASE1 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "SHORT_UUID_BASE", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROTOCOL_SCHEME_L2CAP2 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROTOCOL_SCHEME_L2CAP", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROTOCOL_SCHEME_RFCOMM3 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROTOCOL_SCHEME_RFCOMM", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROTOCOL_SCHEME_BT_OBEX4 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROTOCOL_SCHEME_BT_OBEX", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROTOCOL_SCHEME_TCP_OBEX5 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROTOCOL_SCHEME_TCP_OBEX", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_L2CAP_PROTOCOL_UUID6 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "L2CAP_PROTOCOL_UUID", "Ljavax/bluetooth/UUID;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_RFCOMM_PROTOCOL_UUID7 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "RFCOMM_PROTOCOL_UUID", "Ljavax/bluetooth/UUID;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_OBEX_PROTOCOL_UUID8 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "OBEX_PROTOCOL_UUID", "Ljavax/bluetooth/UUID;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_OBEXFileTransferServiceClass_UUID9 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "OBEXFileTransferServiceClass_UUID", "Ljavax/bluetooth/UUID;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_RFCOMM_CHANNEL_MIN10 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "RFCOMM_CHANNEL_MIN", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_RFCOMM_CHANNEL_MAX11 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "RFCOMM_CHANNEL_MAX", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_L2CAP_PSM_MIN12 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "L2CAP_PSM_MIN", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_L2CAP_PSM_MIN_JSR_8213 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "L2CAP_PSM_MIN_JSR_82", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_L2CAP_PSM_MAX14 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "L2CAP_PSM_MAX", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_TCP_OBEX_DEFAULT_PORT15 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "TCP_OBEX_DEFAULT_PORT", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_API_VERSION16 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_API_VERSION", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_OBEX_API_VERSION17 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_OBEX_API_VERSION", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_MASTER_SWITCH18 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_MASTER_SWITCH", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_SD_ATTR_RETRIEVABLE_MAX19 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_SD_ATTR_RETRIEVABLE_MAX", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_DEVICES_MAX20 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_CONNECTED_DEVICES_MAX", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_L2CAP_RECEIVEMTU_MAX21 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_L2CAP_RECEIVEMTU_MAX", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_SD_TRANS_MAX22 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_SD_TRANS_MAX", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_INQUIRY_SCAN23 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_CONNECTED_INQUIRY_SCAN", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_PAGE_SCAN24 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_CONNECTED_PAGE_SCAN", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_INQUIRY25 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_CONNECTED_INQUIRY", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_PROPERTY_BLUETOOTH_CONNECTED_PAGE26 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "PROPERTY_BLUETOOTH_CONNECTED_PAGE", "Ljava/lang/String;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_SERIAL_PORT_UUID27 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "SERIAL_PORT_UUID", "Ljavax/bluetooth/UUID;");
            global::com.intel.bluetooth.BluetoothConsts.j4n_BluetoothProfileDescriptorList28 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "BluetoothProfileDescriptorList", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_BrowseGroupList29 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "BrowseGroupList", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ClientExecutableURL30 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ClientExecutableURL", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_DocumentationURL31 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "DocumentationURL", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_IconURL32 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "IconURL", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_LanguageBasedAttributeIDList33 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "LanguageBasedAttributeIDList", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ProtocolDescriptorList34 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ProtocolDescriptorList", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ProviderName35 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ProviderName", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceAvailability36 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceAvailability", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceClassIDList37 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceClassIDList", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceDatabaseState38 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceDatabaseState", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceDescription39 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceDescription", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceID40 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceID", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceInfoTimeToLive41 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceInfoTimeToLive", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_AttributeIDServiceName42 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "AttributeIDServiceName", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceName43 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceName", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceRecordHandle44 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceRecordHandle", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_ServiceRecordState45 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "ServiceRecordState", "I");
            global::com.intel.bluetooth.BluetoothConsts.j4n_VersionNumberList46 = @__env.GetStaticFieldID(global::com.intel.bluetooth.BluetoothConsts.staticClass, "VersionNumberList", "I");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/DeviceClass;)Ljava/lang/String;")]
        public static global::java.lang.String toString(global::javax.bluetooth.DeviceClass par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallStaticObjectMethodPtr(global::com.intel.bluetooth.BluetoothConsts.staticClass, global::com.intel.bluetooth.BluetoothConsts.j4n_toString0, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.BluetoothConsts(@__env);
            }
        }
    }
    #endregion
}
