//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface BlueCoveConfigProperties {
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class BlueCoveConfigProperties_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_DEBUG {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_DEBUG0));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_DEBUG_STDOUT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_DEBUG_STDOUT1));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_DEBUG_LOG4J {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_DEBUG_LOG4J2));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_STACK {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_STACK3));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_STACK_FIRST {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_STACK_FIRST4));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_NATIVE_RESOURCE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_NATIVE_RESOURCE5));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_NATIVE_PATH {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_NATIVE_PATH6));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_BLUEZ_CLASS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_BLUEZ_CLASS7));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_LOCAL_DEVICE_ID {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_LOCAL_DEVICE_ID8));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_LOCAL_DEVICE_ADDRESS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_LOCAL_DEVICE_ADDRESS9));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_EMULATOR_CLASS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_EMULATOR_CLASS10));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_EMULATOR_HOST {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_EMULATOR_HOST11));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_EMULATOR_PORT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_EMULATOR_PORT12));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_EMULATOR_RMI_REGISTRY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_EMULATOR_RMI_REGISTRY13));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("[Ljava/lang/String;")]
        public static global::java.lang.String[] INITIALIZATION_PROPERTIES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_INITIALIZATION_PROPERTIES14));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_CONNECT_TIMEOUT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_CONNECT_TIMEOUT15));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_CONNECT_UNREACHABLE_RETRY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_CONNECT_UNREACHABLE_RETRY16));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_INQUIRY_DURATION {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_INQUIRY_DURATION17));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int PROPERTY_INQUIRY_DURATION_DEFAULT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_INQUIRY_DURATION_DEFAULT18)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_INQUIRY_REPORT_ASAP {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_INQUIRY_REPORT_ASAP19));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_OBEX_MTU {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_OBEX_MTU20));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_OBEX_TIMEOUT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_OBEX_TIMEOUT21));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_JSR_82_PSM_MINIMUM_OFF {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_JSR_82_PSM_MINIMUM_OFF22));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Ljava/lang/String;")]
        public static global::java.lang.String PROPERTY_SDP_STRING_ENCODING_ASCII {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.GetStaticObjectFieldPtr(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_SDP_STRING_ENCODING_ASCII23));
            }
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::com.intel.bluetooth.BlueCoveConfigProperties), typeof(global::com.intel.bluetooth.BlueCoveConfigProperties_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::com.intel.bluetooth.BlueCoveConfigProperties), typeof(global::com.intel.bluetooth.BlueCoveConfigProperties_))]
    internal sealed partial class @__BlueCoveConfigProperties : global::java.lang.Object, global::com.intel.bluetooth.BlueCoveConfigProperties {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_DEBUG0;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_DEBUG_STDOUT1;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_DEBUG_LOG4J2;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_STACK3;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_STACK_FIRST4;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_NATIVE_RESOURCE5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_NATIVE_PATH6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_BLUEZ_CLASS7;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_LOCAL_DEVICE_ID8;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_LOCAL_DEVICE_ADDRESS9;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_EMULATOR_CLASS10;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_EMULATOR_HOST11;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_EMULATOR_PORT12;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_EMULATOR_RMI_REGISTRY13;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INITIALIZATION_PROPERTIES14;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_CONNECT_TIMEOUT15;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_CONNECT_UNREACHABLE_RETRY16;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_INQUIRY_DURATION17;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_INQUIRY_DURATION_DEFAULT18;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_INQUIRY_REPORT_ASAP19;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_OBEX_MTU20;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_OBEX_TIMEOUT21;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_JSR_82_PSM_MINIMUM_OFF22;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PROPERTY_SDP_STRING_ENCODING_ASCII23;
        
        private @__BlueCoveConfigProperties(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass = @__class;
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_DEBUG0 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_DEBUG", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_DEBUG_STDOUT1 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_DEBUG_STDOUT", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_DEBUG_LOG4J2 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_DEBUG_LOG4J", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_STACK3 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_STACK", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_STACK_FIRST4 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_STACK_FIRST", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_NATIVE_RESOURCE5 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_NATIVE_RESOURCE", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_NATIVE_PATH6 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_NATIVE_PATH", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_BLUEZ_CLASS7 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_BLUEZ_CLASS", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_LOCAL_DEVICE_ID8 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_LOCAL_DEVICE_ID", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_LOCAL_DEVICE_ADDRESS9 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_LOCAL_DEVICE_ADDRESS", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_EMULATOR_CLASS10 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_EMULATOR_CLASS", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_EMULATOR_HOST11 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_EMULATOR_HOST", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_EMULATOR_PORT12 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_EMULATOR_PORT", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_EMULATOR_RMI_REGISTRY13 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_EMULATOR_RMI_REGISTRY", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_INITIALIZATION_PROPERTIES14 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "INITIALIZATION_PROPERTIES", "[Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_CONNECT_TIMEOUT15 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_CONNECT_TIMEOUT", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_CONNECT_UNREACHABLE_RETRY16 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_CONNECT_UNREACHABLE_RETRY", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_INQUIRY_DURATION17 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_INQUIRY_DURATION", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_INQUIRY_DURATION_DEFAULT18 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_INQUIRY_DURATION_DEFAULT", "I");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_INQUIRY_REPORT_ASAP19 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_INQUIRY_REPORT_ASAP", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_OBEX_MTU20 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_OBEX_MTU", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_OBEX_TIMEOUT21 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_OBEX_TIMEOUT", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_JSR_82_PSM_MINIMUM_OFF22 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_JSR_82_PSM_MINIMUM_OFF", "Ljava/lang/String;");
            global::com.intel.bluetooth.@__BlueCoveConfigProperties.j4n_PROPERTY_SDP_STRING_ENCODING_ASCII23 = @__env.GetStaticFieldID(global::com.intel.bluetooth.@__BlueCoveConfigProperties.staticClass, "PROPERTY_SDP_STRING_ENCODING_ASCII", "Ljava/lang/String;");
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__BlueCoveConfigProperties);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            return methods;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.@__BlueCoveConfigProperties(@__env);
            }
        }
    }
    #endregion
}
