//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class UtilsJavaSE : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_initCause0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_threadSetDaemon1;
        
        protected UtilsJavaSE(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.UtilsJavaSE.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.UtilsJavaSE.staticClass = @__class;
            global::com.intel.bluetooth.UtilsJavaSE.j4n_initCause0 = @__env.GetStaticMethodID(global::com.intel.bluetooth.UtilsJavaSE.staticClass, "initCause", "(Ljava/lang/Throwable;Ljava/lang/Throwable;)Ljava/lang/Throwable;");
            global::com.intel.bluetooth.UtilsJavaSE.j4n_threadSetDaemon1 = @__env.GetStaticMethodID(global::com.intel.bluetooth.UtilsJavaSE.staticClass, "threadSetDaemon", "(Ljava/lang/Thread;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Throwable;Ljava/lang/Throwable;)Ljava/lang/Throwable;")]
        public static global::java.lang.Throwable initCause(global::java.lang.Throwable par0, global::java.lang.Throwable par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Throwable>(@__env, @__env.CallStaticObjectMethodPtr(global::com.intel.bluetooth.UtilsJavaSE.staticClass, global::com.intel.bluetooth.UtilsJavaSE.j4n_initCause0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Throwable>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Throwable>(@__env, par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/Thread;)V")]
        public static void threadSetDaemon(global::java.lang.Object par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallStaticVoidMethod(global::com.intel.bluetooth.UtilsJavaSE.staticClass, global::com.intel.bluetooth.UtilsJavaSE.j4n_threadSetDaemon1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.UtilsJavaSE(@__env);
            }
        }
    }
    #endregion
}
