//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.microedition.io {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface InputConnection : global::javax.microedition.io.Connection {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/DataInputStream;")]
        global::java.io.InputStream openDataInputStream();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/InputStream;")]
        global::java.io.InputStream openInputStream();
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class InputConnection_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.microedition.io.@__InputConnection.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::javax.microedition.io.InputConnection), typeof(global::javax.microedition.io.InputConnection_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::javax.microedition.io.InputConnection), typeof(global::javax.microedition.io.InputConnection_))]
    internal sealed partial class @__InputConnection : global::java.lang.Object, global::javax.microedition.io.InputConnection {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_close0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_openDataInputStream1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_openInputStream2;
        
        private @__InputConnection(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.microedition.io.@__InputConnection.staticClass = @__class;
            global::javax.microedition.io.@__InputConnection.j4n_close0 = @__env.GetMethodID(global::javax.microedition.io.@__InputConnection.staticClass, "close", "()V");
            global::javax.microedition.io.@__InputConnection.j4n_openDataInputStream1 = @__env.GetMethodID(global::javax.microedition.io.@__InputConnection.staticClass, "openDataInputStream", "()Ljava/io/DataInputStream;");
            global::javax.microedition.io.@__InputConnection.j4n_openInputStream2 = @__env.GetMethodID(global::javax.microedition.io.@__InputConnection.staticClass, "openInputStream", "()Ljava/io/InputStream;");
        }
        
        public void close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::javax.microedition.io.@__InputConnection.j4n_close0);
            }
        }
        
        public global::java.io.InputStream openDataInputStream() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.InputStream>(@__env, @__env.CallObjectMethodPtr(this, global::javax.microedition.io.@__InputConnection.j4n_openDataInputStream1));
            }
        }
        
        public global::java.io.InputStream openInputStream() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.InputStream>(@__env, @__env.CallObjectMethodPtr(this, global::javax.microedition.io.@__InputConnection.j4n_openInputStream2));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__InputConnection);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "close", "close0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "openDataInputStream", "openDataInputStream1", "()Ljava/io/DataInputStream;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "openInputStream", "openInputStream2", "()Ljava/io/InputStream;"));
            return methods;
        }
        
        private static void close0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.microedition.io.InputConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.microedition.io.InputConnection>(@__env, @__obj);
            ((global::javax.microedition.io.Connection)(@__real)).close();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle openDataInputStream1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/io/DataInputStream;
            // ()Ljava/io/InputStream;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.microedition.io.InputConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.microedition.io.InputConnection>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.openDataInputStream());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle openInputStream2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/io/InputStream;
            // ()Ljava/io/InputStream;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.microedition.io.InputConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.microedition.io.InputConnection>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.openInputStream());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.microedition.io.@__InputConnection(@__env);
            }
        }
    }
    #endregion
}
