//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    [global::System.SerializableAttribute()]
    public partial class BluetoothConnectionException : global::java.lang.Exception {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getStatus0;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_UNKNOWN_PSM1;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_SECURITY_BLOCK2;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_NO_RESOURCES3;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_FAILED_NOINFO4;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_TIMEOUT5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_UNACCEPTABLE_PARAMS6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorBluetoothConnectionException7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorBluetoothConnectionException8;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)V")]
        public BluetoothConnectionException(int par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::javax.bluetooth.BluetoothConnectionException.staticClass, global::javax.bluetooth.BluetoothConnectionException.j4n__ctorBluetoothConnectionException7, this, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(ILjava/lang/String;)V")]
        public BluetoothConnectionException(int par0, global::java.lang.String par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::javax.bluetooth.BluetoothConnectionException.staticClass, global::javax.bluetooth.BluetoothConnectionException.j4n__ctorBluetoothConnectionException8, this, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1));
            }
        }
        
        protected BluetoothConnectionException(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        protected BluetoothConnectionException(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.bluetooth.BluetoothConnectionException.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int UNKNOWN_PSM {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.BluetoothConnectionException.staticClass, global::javax.bluetooth.BluetoothConnectionException.j4n_UNKNOWN_PSM1)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int SECURITY_BLOCK {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.BluetoothConnectionException.staticClass, global::javax.bluetooth.BluetoothConnectionException.j4n_SECURITY_BLOCK2)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int NO_RESOURCES {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.BluetoothConnectionException.staticClass, global::javax.bluetooth.BluetoothConnectionException.j4n_NO_RESOURCES3)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int FAILED_NOINFO {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.BluetoothConnectionException.staticClass, global::javax.bluetooth.BluetoothConnectionException.j4n_FAILED_NOINFO4)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int TIMEOUT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.BluetoothConnectionException.staticClass, global::javax.bluetooth.BluetoothConnectionException.j4n_TIMEOUT5)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int UNACCEPTABLE_PARAMS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.BluetoothConnectionException.staticClass, global::javax.bluetooth.BluetoothConnectionException.j4n_UNACCEPTABLE_PARAMS6)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.bluetooth.BluetoothConnectionException.staticClass = @__class;
            global::javax.bluetooth.BluetoothConnectionException.j4n_getStatus0 = @__env.GetMethodID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "getStatus", "()I");
            global::javax.bluetooth.BluetoothConnectionException.j4n_UNKNOWN_PSM1 = @__env.GetStaticFieldID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "UNKNOWN_PSM", "I");
            global::javax.bluetooth.BluetoothConnectionException.j4n_SECURITY_BLOCK2 = @__env.GetStaticFieldID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "SECURITY_BLOCK", "I");
            global::javax.bluetooth.BluetoothConnectionException.j4n_NO_RESOURCES3 = @__env.GetStaticFieldID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "NO_RESOURCES", "I");
            global::javax.bluetooth.BluetoothConnectionException.j4n_FAILED_NOINFO4 = @__env.GetStaticFieldID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "FAILED_NOINFO", "I");
            global::javax.bluetooth.BluetoothConnectionException.j4n_TIMEOUT5 = @__env.GetStaticFieldID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "TIMEOUT", "I");
            global::javax.bluetooth.BluetoothConnectionException.j4n_UNACCEPTABLE_PARAMS6 = @__env.GetStaticFieldID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "UNACCEPTABLE_PARAMS", "I");
            global::javax.bluetooth.BluetoothConnectionException.j4n__ctorBluetoothConnectionException7 = @__env.GetMethodID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "<init>", "(I)V");
            global::javax.bluetooth.BluetoothConnectionException.j4n__ctorBluetoothConnectionException8 = @__env.GetMethodID(global::javax.bluetooth.BluetoothConnectionException.staticClass, "<init>", "(ILjava/lang/String;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getStatus() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.BluetoothConnectionException.j4n_getStatus0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.bluetooth.BluetoothConnectionException(@__env);
            }
        }
    }
    #endregion
}
