//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class DataElement : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getBoolean0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getLong1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getValue2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_addElement3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSize4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_insertElementAt5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_removeElement6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getDataType7;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_NULL8;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_U_INT_19;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_U_INT_210;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_U_INT_411;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_U_INT_812;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_U_INT_1613;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INT_114;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INT_215;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INT_416;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INT_817;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_INT_1618;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_URL19;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_UUID20;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_BOOL21;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_STRING22;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DATSEQ23;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DATALT24;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorDataElement25;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorDataElement26;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorDataElement27;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorDataElement28;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(ILjava/lang/Object;)V")]
        public DataElement(int par0, global::java.lang.Object par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n__ctorDataElement25, this, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(IJ)V")]
        public DataElement(int par0, long par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n__ctorDataElement26, this, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Z)V")]
        public DataElement(bool par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n__ctorDataElement27, this, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)V")]
        public DataElement(int par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n__ctorDataElement28, this, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        protected DataElement(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.bluetooth.DataElement.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int NULL {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_NULL8)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int U_INT_1 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_U_INT_19)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int U_INT_2 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_U_INT_210)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int U_INT_4 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_U_INT_411)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int U_INT_8 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_U_INT_812)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int U_INT_16 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_U_INT_1613)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int INT_1 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_INT_114)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int INT_2 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_INT_215)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int INT_4 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_INT_416)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int INT_8 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_INT_817)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int INT_16 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_INT_1618)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int URL {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_URL19)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int UUID {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_UUID20)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int BOOL {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_BOOL21)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int STRING {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_STRING22)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int DATSEQ {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_DATSEQ23)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int DATALT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DataElement.staticClass, global::javax.bluetooth.DataElement.j4n_DATALT24)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.bluetooth.DataElement.staticClass = @__class;
            global::javax.bluetooth.DataElement.j4n_getBoolean0 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "getBoolean", "()Z");
            global::javax.bluetooth.DataElement.j4n_getLong1 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "getLong", "()J");
            global::javax.bluetooth.DataElement.j4n_getValue2 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "getValue", "()Ljava/lang/Object;");
            global::javax.bluetooth.DataElement.j4n_addElement3 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "addElement", "(Ljavax/bluetooth/DataElement;)V");
            global::javax.bluetooth.DataElement.j4n_getSize4 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "getSize", "()I");
            global::javax.bluetooth.DataElement.j4n_insertElementAt5 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "insertElementAt", "(Ljavax/bluetooth/DataElement;I)V");
            global::javax.bluetooth.DataElement.j4n_removeElement6 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "removeElement", "(Ljavax/bluetooth/DataElement;)Z");
            global::javax.bluetooth.DataElement.j4n_getDataType7 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "getDataType", "()I");
            global::javax.bluetooth.DataElement.j4n_NULL8 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "NULL", "I");
            global::javax.bluetooth.DataElement.j4n_U_INT_19 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "U_INT_1", "I");
            global::javax.bluetooth.DataElement.j4n_U_INT_210 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "U_INT_2", "I");
            global::javax.bluetooth.DataElement.j4n_U_INT_411 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "U_INT_4", "I");
            global::javax.bluetooth.DataElement.j4n_U_INT_812 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "U_INT_8", "I");
            global::javax.bluetooth.DataElement.j4n_U_INT_1613 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "U_INT_16", "I");
            global::javax.bluetooth.DataElement.j4n_INT_114 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "INT_1", "I");
            global::javax.bluetooth.DataElement.j4n_INT_215 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "INT_2", "I");
            global::javax.bluetooth.DataElement.j4n_INT_416 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "INT_4", "I");
            global::javax.bluetooth.DataElement.j4n_INT_817 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "INT_8", "I");
            global::javax.bluetooth.DataElement.j4n_INT_1618 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "INT_16", "I");
            global::javax.bluetooth.DataElement.j4n_URL19 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "URL", "I");
            global::javax.bluetooth.DataElement.j4n_UUID20 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "UUID", "I");
            global::javax.bluetooth.DataElement.j4n_BOOL21 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "BOOL", "I");
            global::javax.bluetooth.DataElement.j4n_STRING22 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "STRING", "I");
            global::javax.bluetooth.DataElement.j4n_DATSEQ23 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "DATSEQ", "I");
            global::javax.bluetooth.DataElement.j4n_DATALT24 = @__env.GetStaticFieldID(global::javax.bluetooth.DataElement.staticClass, "DATALT", "I");
            global::javax.bluetooth.DataElement.j4n__ctorDataElement25 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "<init>", "(ILjava/lang/Object;)V");
            global::javax.bluetooth.DataElement.j4n__ctorDataElement26 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "<init>", "(IJ)V");
            global::javax.bluetooth.DataElement.j4n__ctorDataElement27 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "<init>", "(Z)V");
            global::javax.bluetooth.DataElement.j4n__ctorDataElement28 = @__env.GetMethodID(global::javax.bluetooth.DataElement.staticClass, "<init>", "(I)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool getBoolean() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.DataElement.j4n_getBoolean0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        public virtual long getLong() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::javax.bluetooth.DataElement.j4n_getLong1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/Object;")]
        public virtual global::java.lang.Object getValue() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.DataElement.j4n_getValue2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/DataElement;)V")]
        public virtual void addElement(global::javax.bluetooth.DataElement par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::javax.bluetooth.DataElement.j4n_addElement3, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getSize() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.DataElement.j4n_getSize4)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/DataElement;I)V")]
        public virtual void insertElementAt(global::javax.bluetooth.DataElement par0, int par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::javax.bluetooth.DataElement.j4n_insertElementAt5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/DataElement;)Z")]
        public virtual bool removeElement(global::javax.bluetooth.DataElement par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.DataElement.j4n_removeElement6, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getDataType() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.DataElement.j4n_getDataType7)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.bluetooth.DataElement(@__env);
            }
        }
    }
    #endregion
}
