//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class DeviceClass : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getServiceClasses0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getMajorDeviceClass1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getMinorDeviceClass2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorDeviceClass3;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)V")]
        public DeviceClass(int par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::javax.bluetooth.DeviceClass.staticClass, global::javax.bluetooth.DeviceClass.j4n__ctorDeviceClass3, this, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        protected DeviceClass(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.bluetooth.DeviceClass.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.bluetooth.DeviceClass.staticClass = @__class;
            global::javax.bluetooth.DeviceClass.j4n_getServiceClasses0 = @__env.GetMethodID(global::javax.bluetooth.DeviceClass.staticClass, "getServiceClasses", "()I");
            global::javax.bluetooth.DeviceClass.j4n_getMajorDeviceClass1 = @__env.GetMethodID(global::javax.bluetooth.DeviceClass.staticClass, "getMajorDeviceClass", "()I");
            global::javax.bluetooth.DeviceClass.j4n_getMinorDeviceClass2 = @__env.GetMethodID(global::javax.bluetooth.DeviceClass.staticClass, "getMinorDeviceClass", "()I");
            global::javax.bluetooth.DeviceClass.j4n__ctorDeviceClass3 = @__env.GetMethodID(global::javax.bluetooth.DeviceClass.staticClass, "<init>", "(I)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getServiceClasses() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.DeviceClass.j4n_getServiceClasses0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getMajorDeviceClass() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.DeviceClass.j4n_getMajorDeviceClass1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getMinorDeviceClass() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.DeviceClass.j4n_getMinorDeviceClass2)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.bluetooth.DeviceClass(@__env);
            }
        }
    }
    #endregion
}
