//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class DiscoveryAgent : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_startInquiry0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_searchServices1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_cancelInquiry2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_retrieveDevices3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_cancelServiceSearch4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_selectService5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_NOT_DISCOVERABLE6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_GIAC7;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_LIAC8;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_CACHED9;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_PREKNOWN10;
        
        protected DiscoveryAgent(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.bluetooth.DiscoveryAgent.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int NOT_DISCOVERABLE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DiscoveryAgent.staticClass, global::javax.bluetooth.DiscoveryAgent.j4n_NOT_DISCOVERABLE6)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int GIAC {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DiscoveryAgent.staticClass, global::javax.bluetooth.DiscoveryAgent.j4n_GIAC7)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int LIAC {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DiscoveryAgent.staticClass, global::javax.bluetooth.DiscoveryAgent.j4n_LIAC8)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int CACHED {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DiscoveryAgent.staticClass, global::javax.bluetooth.DiscoveryAgent.j4n_CACHED9)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int PREKNOWN {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.DiscoveryAgent.staticClass, global::javax.bluetooth.DiscoveryAgent.j4n_PREKNOWN10)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.bluetooth.DiscoveryAgent.staticClass = @__class;
            global::javax.bluetooth.DiscoveryAgent.j4n_startInquiry0 = @__env.GetMethodID(global::javax.bluetooth.DiscoveryAgent.staticClass, "startInquiry", "(ILjavax/bluetooth/DiscoveryListener;)Z");
            global::javax.bluetooth.DiscoveryAgent.j4n_searchServices1 = @__env.GetMethodID(global::javax.bluetooth.DiscoveryAgent.staticClass, "searchServices", "([I[Ljavax/bluetooth/UUID;Ljavax/bluetooth/RemoteDevice;Ljavax/bluetooth/Discover" +
                    "yListener;)I");
            global::javax.bluetooth.DiscoveryAgent.j4n_cancelInquiry2 = @__env.GetMethodID(global::javax.bluetooth.DiscoveryAgent.staticClass, "cancelInquiry", "(Ljavax/bluetooth/DiscoveryListener;)Z");
            global::javax.bluetooth.DiscoveryAgent.j4n_retrieveDevices3 = @__env.GetMethodID(global::javax.bluetooth.DiscoveryAgent.staticClass, "retrieveDevices", "(I)[Ljavax/bluetooth/RemoteDevice;");
            global::javax.bluetooth.DiscoveryAgent.j4n_cancelServiceSearch4 = @__env.GetMethodID(global::javax.bluetooth.DiscoveryAgent.staticClass, "cancelServiceSearch", "(I)Z");
            global::javax.bluetooth.DiscoveryAgent.j4n_selectService5 = @__env.GetMethodID(global::javax.bluetooth.DiscoveryAgent.staticClass, "selectService", "(Ljavax/bluetooth/UUID;IZ)Ljava/lang/String;");
            global::javax.bluetooth.DiscoveryAgent.j4n_NOT_DISCOVERABLE6 = @__env.GetStaticFieldID(global::javax.bluetooth.DiscoveryAgent.staticClass, "NOT_DISCOVERABLE", "I");
            global::javax.bluetooth.DiscoveryAgent.j4n_GIAC7 = @__env.GetStaticFieldID(global::javax.bluetooth.DiscoveryAgent.staticClass, "GIAC", "I");
            global::javax.bluetooth.DiscoveryAgent.j4n_LIAC8 = @__env.GetStaticFieldID(global::javax.bluetooth.DiscoveryAgent.staticClass, "LIAC", "I");
            global::javax.bluetooth.DiscoveryAgent.j4n_CACHED9 = @__env.GetStaticFieldID(global::javax.bluetooth.DiscoveryAgent.staticClass, "CACHED", "I");
            global::javax.bluetooth.DiscoveryAgent.j4n_PREKNOWN10 = @__env.GetStaticFieldID(global::javax.bluetooth.DiscoveryAgent.staticClass, "PREKNOWN", "I");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(ILjavax/bluetooth/DiscoveryListener;)Z")]
        public virtual bool startInquiry(int par0, global::javax.bluetooth.DiscoveryListener par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.DiscoveryAgent.j4n_startInquiry0, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.bluetooth.DiscoveryListener>(@__env, par1))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([I[Ljavax/bluetooth/UUID;Ljavax/bluetooth/RemoteDevice;Ljavax/bluetooth/Discover" +
            "yListener;)I")]
        public virtual int searchServices(int[] par0, global::javax.bluetooth.UUID[] par1, global::javax.bluetooth.RemoteDevice par2, global::javax.bluetooth.DiscoveryListener par3) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 18)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.DiscoveryAgent.j4n_searchServices1, global::net.sf.jni4net.utils.Convertor.ParArrayPrimC2J(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParArrayStrongCp2J(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par2), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.bluetooth.DiscoveryListener>(@__env, par3))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/DiscoveryListener;)Z")]
        public virtual bool cancelInquiry(global::javax.bluetooth.DiscoveryListener par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.DiscoveryAgent.j4n_cancelInquiry2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.bluetooth.DiscoveryListener>(@__env, par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)[Ljavax/bluetooth/RemoteDevice;")]
        public virtual global::javax.bluetooth.RemoteDevice[] retrieveDevices(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2Cp<global::javax.bluetooth.RemoteDevice[], global::javax.bluetooth.RemoteDevice>(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.DiscoveryAgent.j4n_retrieveDevices3, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)Z")]
        public virtual bool cancelServiceSearch(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.DiscoveryAgent.j4n_cancelServiceSearch4, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/UUID;IZ)Ljava/lang/String;")]
        public virtual global::java.lang.String selectService(global::javax.bluetooth.UUID par0, int par1, bool par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.DiscoveryAgent.j4n_selectService5, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.bluetooth.DiscoveryAgent(@__env);
            }
        }
    }
    #endregion
}
