//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface L2CAPConnection : global::javax.microedition.io.Connection {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        bool ready();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        int getTransmitMTU();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        int getReceiveMTU();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([B)V")]
        void send(byte[] par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([B)I")]
        int receive(byte[] par0);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class L2CAPConnection_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.bluetooth.@__L2CAPConnection.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int DEFAULT_MTU {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.@__L2CAPConnection.staticClass, global::javax.bluetooth.@__L2CAPConnection.j4n_DEFAULT_MTU6)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int MINIMUM_MTU {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.@__L2CAPConnection.staticClass, global::javax.bluetooth.@__L2CAPConnection.j4n_MINIMUM_MTU7)));
            }
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::javax.bluetooth.L2CAPConnection), typeof(global::javax.bluetooth.L2CAPConnection_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::javax.bluetooth.L2CAPConnection), typeof(global::javax.bluetooth.L2CAPConnection_))]
    internal sealed partial class @__L2CAPConnection : global::java.lang.Object, global::javax.bluetooth.L2CAPConnection {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_close0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_ready1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getTransmitMTU2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getReceiveMTU3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_send4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_receive5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DEFAULT_MTU6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_MINIMUM_MTU7;
        
        private @__L2CAPConnection(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.bluetooth.@__L2CAPConnection.staticClass = @__class;
            global::javax.bluetooth.@__L2CAPConnection.j4n_close0 = @__env.GetMethodID(global::javax.bluetooth.@__L2CAPConnection.staticClass, "close", "()V");
            global::javax.bluetooth.@__L2CAPConnection.j4n_ready1 = @__env.GetMethodID(global::javax.bluetooth.@__L2CAPConnection.staticClass, "ready", "()Z");
            global::javax.bluetooth.@__L2CAPConnection.j4n_getTransmitMTU2 = @__env.GetMethodID(global::javax.bluetooth.@__L2CAPConnection.staticClass, "getTransmitMTU", "()I");
            global::javax.bluetooth.@__L2CAPConnection.j4n_getReceiveMTU3 = @__env.GetMethodID(global::javax.bluetooth.@__L2CAPConnection.staticClass, "getReceiveMTU", "()I");
            global::javax.bluetooth.@__L2CAPConnection.j4n_send4 = @__env.GetMethodID(global::javax.bluetooth.@__L2CAPConnection.staticClass, "send", "([B)V");
            global::javax.bluetooth.@__L2CAPConnection.j4n_receive5 = @__env.GetMethodID(global::javax.bluetooth.@__L2CAPConnection.staticClass, "receive", "([B)I");
            global::javax.bluetooth.@__L2CAPConnection.j4n_DEFAULT_MTU6 = @__env.GetStaticFieldID(global::javax.bluetooth.@__L2CAPConnection.staticClass, "DEFAULT_MTU", "I");
            global::javax.bluetooth.@__L2CAPConnection.j4n_MINIMUM_MTU7 = @__env.GetStaticFieldID(global::javax.bluetooth.@__L2CAPConnection.staticClass, "MINIMUM_MTU", "I");
        }
        
        public void close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::javax.bluetooth.@__L2CAPConnection.j4n_close0);
            }
        }
        
        public bool ready() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.@__L2CAPConnection.j4n_ready1)));
            }
        }
        
        public int getTransmitMTU() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.@__L2CAPConnection.j4n_getTransmitMTU2)));
            }
        }
        
        public int getReceiveMTU() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.@__L2CAPConnection.j4n_getReceiveMTU3)));
            }
        }
        
        public void send(byte[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::javax.bluetooth.@__L2CAPConnection.j4n_send4, global::net.sf.jni4net.utils.Convertor.ParArrayPrimC2J(@__env, par0));
            }
        }
        
        public int receive(byte[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::javax.bluetooth.@__L2CAPConnection.j4n_receive5, global::net.sf.jni4net.utils.Convertor.ParArrayPrimC2J(@__env, par0))));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__L2CAPConnection);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "close", "close0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ready", "ready1", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getTransmitMTU", "getTransmitMTU2", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getReceiveMTU", "getReceiveMTU3", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "send", "send4", "([B)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "receive", "receive5", "([B)I"));
            return methods;
        }
        
        private static void close0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.bluetooth.L2CAPConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.L2CAPConnection>(@__env, @__obj);
            ((global::javax.microedition.io.Connection)(@__real)).close();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool ready1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::javax.bluetooth.L2CAPConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.L2CAPConnection>(@__env, @__obj);
            @__return = ((bool)(@__real.ready()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int getTransmitMTU2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::javax.bluetooth.L2CAPConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.L2CAPConnection>(@__env, @__obj);
            @__return = ((int)(@__real.getTransmitMTU()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int getReceiveMTU3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::javax.bluetooth.L2CAPConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.L2CAPConnection>(@__env, @__obj);
            @__return = ((int)(@__real.getReceiveMTU()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void send4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // ([B)V
            // ([B)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.bluetooth.L2CAPConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.L2CAPConnection>(@__env, @__obj);
            @__real.send(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cbyte(@__env, par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int receive5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // ([B)I
            // ([B)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::javax.bluetooth.L2CAPConnection @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.L2CAPConnection>(@__env, @__obj);
            @__return = ((int)(@__real.receive(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cbyte(@__env, par0))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.bluetooth.@__L2CAPConnection(@__env);
            }
        }
    }
    #endregion
}
