//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class RemoteDevice : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isAuthorized0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_encrypt1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_authenticate2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_authorize3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getRemoteDevice4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getBluetoothAddress5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isTrustedDevice6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isAuthenticated7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isEncrypted8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getFriendlyName9;
        
        protected RemoteDevice(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.bluetooth.RemoteDevice.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.bluetooth.RemoteDevice.staticClass = @__class;
            global::javax.bluetooth.RemoteDevice.j4n_isAuthorized0 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "isAuthorized", "(Ljavax/microedition/io/Connection;)Z");
            global::javax.bluetooth.RemoteDevice.j4n_encrypt1 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "encrypt", "(Ljavax/microedition/io/Connection;Z)Z");
            global::javax.bluetooth.RemoteDevice.j4n_authenticate2 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "authenticate", "()Z");
            global::javax.bluetooth.RemoteDevice.j4n_authorize3 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "authorize", "(Ljavax/microedition/io/Connection;)Z");
            global::javax.bluetooth.RemoteDevice.j4n_getRemoteDevice4 = @__env.GetStaticMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "getRemoteDevice", "(Ljavax/microedition/io/Connection;)Ljavax/bluetooth/RemoteDevice;");
            global::javax.bluetooth.RemoteDevice.j4n_getBluetoothAddress5 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "getBluetoothAddress", "()Ljava/lang/String;");
            global::javax.bluetooth.RemoteDevice.j4n_isTrustedDevice6 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "isTrustedDevice", "()Z");
            global::javax.bluetooth.RemoteDevice.j4n_isAuthenticated7 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "isAuthenticated", "()Z");
            global::javax.bluetooth.RemoteDevice.j4n_isEncrypted8 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "isEncrypted", "()Z");
            global::javax.bluetooth.RemoteDevice.j4n_getFriendlyName9 = @__env.GetMethodID(global::javax.bluetooth.RemoteDevice.staticClass, "getFriendlyName", "(Z)Ljava/lang/String;");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/microedition/io/Connection;)Z")]
        public virtual bool isAuthorized(global::javax.microedition.io.Connection par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.RemoteDevice.j4n_isAuthorized0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.microedition.io.Connection>(@__env, par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/microedition/io/Connection;Z)Z")]
        public virtual bool encrypt(global::javax.microedition.io.Connection par0, bool par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.RemoteDevice.j4n_encrypt1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.microedition.io.Connection>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool authenticate() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.RemoteDevice.j4n_authenticate2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/microedition/io/Connection;)Z")]
        public virtual bool authorize(global::javax.microedition.io.Connection par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.RemoteDevice.j4n_authorize3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.microedition.io.Connection>(@__env, par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/microedition/io/Connection;)Ljavax/bluetooth/RemoteDevice;")]
        public static global::javax.bluetooth.RemoteDevice getRemoteDevice(global::javax.microedition.io.Connection par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.RemoteDevice>(@__env, @__env.CallStaticObjectMethodPtr(global::javax.bluetooth.RemoteDevice.staticClass, global::javax.bluetooth.RemoteDevice.j4n_getRemoteDevice4, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.microedition.io.Connection>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public global::java.lang.String getBluetoothAddress() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.RemoteDevice.j4n_getBluetoothAddress5));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool isTrustedDevice() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.RemoteDevice.j4n_isTrustedDevice6)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool isAuthenticated() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.RemoteDevice.j4n_isAuthenticated7)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool isEncrypted() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.RemoteDevice.j4n_isEncrypted8)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Z)Ljava/lang/String;")]
        public virtual global::java.lang.String getFriendlyName(bool par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.RemoteDevice.j4n_getFriendlyName9, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.bluetooth.RemoteDevice(@__env);
            }
        }
    }
    #endregion
}
