//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.bluetooth {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface ServiceRecord {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)V")]
        void setDeviceServiceClasses(int par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(ILjavax/bluetooth/DataElement;)Z")]
        bool setAttributeValue(int par0, global::javax.bluetooth.DataElement par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)Ljavax/bluetooth/DataElement;")]
        global::javax.bluetooth.DataElement getAttributeValue(int par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([I)Z")]
        bool populateRecord(int[] par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[I")]
        int[] getAttributeIDs();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(IZ)Ljava/lang/String;")]
        global::java.lang.String getConnectionURL(int par0, bool par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/bluetooth/RemoteDevice;")]
        global::javax.bluetooth.RemoteDevice getHostDevice();
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class ServiceRecord_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.bluetooth.@__ServiceRecord.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int NOAUTHENTICATE_NOENCRYPT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.@__ServiceRecord.staticClass, global::javax.bluetooth.@__ServiceRecord.j4n_NOAUTHENTICATE_NOENCRYPT7)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int AUTHENTICATE_NOENCRYPT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.@__ServiceRecord.staticClass, global::javax.bluetooth.@__ServiceRecord.j4n_AUTHENTICATE_NOENCRYPT8)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int AUTHENTICATE_ENCRYPT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.bluetooth.@__ServiceRecord.staticClass, global::javax.bluetooth.@__ServiceRecord.j4n_AUTHENTICATE_ENCRYPT9)));
            }
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::javax.bluetooth.ServiceRecord), typeof(global::javax.bluetooth.ServiceRecord_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::javax.bluetooth.ServiceRecord), typeof(global::javax.bluetooth.ServiceRecord_))]
    internal sealed partial class @__ServiceRecord : global::java.lang.Object, global::javax.bluetooth.ServiceRecord {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setDeviceServiceClasses0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setAttributeValue1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getAttributeValue2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_populateRecord3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getAttributeIDs4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getConnectionURL5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getHostDevice6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_NOAUTHENTICATE_NOENCRYPT7;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_AUTHENTICATE_NOENCRYPT8;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_AUTHENTICATE_ENCRYPT9;
        
        private @__ServiceRecord(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.bluetooth.@__ServiceRecord.staticClass = @__class;
            global::javax.bluetooth.@__ServiceRecord.j4n_setDeviceServiceClasses0 = @__env.GetMethodID(global::javax.bluetooth.@__ServiceRecord.staticClass, "setDeviceServiceClasses", "(I)V");
            global::javax.bluetooth.@__ServiceRecord.j4n_setAttributeValue1 = @__env.GetMethodID(global::javax.bluetooth.@__ServiceRecord.staticClass, "setAttributeValue", "(ILjavax/bluetooth/DataElement;)Z");
            global::javax.bluetooth.@__ServiceRecord.j4n_getAttributeValue2 = @__env.GetMethodID(global::javax.bluetooth.@__ServiceRecord.staticClass, "getAttributeValue", "(I)Ljavax/bluetooth/DataElement;");
            global::javax.bluetooth.@__ServiceRecord.j4n_populateRecord3 = @__env.GetMethodID(global::javax.bluetooth.@__ServiceRecord.staticClass, "populateRecord", "([I)Z");
            global::javax.bluetooth.@__ServiceRecord.j4n_getAttributeIDs4 = @__env.GetMethodID(global::javax.bluetooth.@__ServiceRecord.staticClass, "getAttributeIDs", "()[I");
            global::javax.bluetooth.@__ServiceRecord.j4n_getConnectionURL5 = @__env.GetMethodID(global::javax.bluetooth.@__ServiceRecord.staticClass, "getConnectionURL", "(IZ)Ljava/lang/String;");
            global::javax.bluetooth.@__ServiceRecord.j4n_getHostDevice6 = @__env.GetMethodID(global::javax.bluetooth.@__ServiceRecord.staticClass, "getHostDevice", "()Ljavax/bluetooth/RemoteDevice;");
            global::javax.bluetooth.@__ServiceRecord.j4n_NOAUTHENTICATE_NOENCRYPT7 = @__env.GetStaticFieldID(global::javax.bluetooth.@__ServiceRecord.staticClass, "NOAUTHENTICATE_NOENCRYPT", "I");
            global::javax.bluetooth.@__ServiceRecord.j4n_AUTHENTICATE_NOENCRYPT8 = @__env.GetStaticFieldID(global::javax.bluetooth.@__ServiceRecord.staticClass, "AUTHENTICATE_NOENCRYPT", "I");
            global::javax.bluetooth.@__ServiceRecord.j4n_AUTHENTICATE_ENCRYPT9 = @__env.GetStaticFieldID(global::javax.bluetooth.@__ServiceRecord.staticClass, "AUTHENTICATE_ENCRYPT", "I");
        }
        
        public void setDeviceServiceClasses(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::javax.bluetooth.@__ServiceRecord.j4n_setDeviceServiceClasses0, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        public bool setAttributeValue(int par0, global::javax.bluetooth.DataElement par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.@__ServiceRecord.j4n_setAttributeValue1, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1))));
            }
        }
        
        public global::javax.bluetooth.DataElement getAttributeValue(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.DataElement>(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.@__ServiceRecord.j4n_getAttributeValue2, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        public bool populateRecord(int[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((bool)(@__env.CallBooleanMethod(this, global::javax.bluetooth.@__ServiceRecord.j4n_populateRecord3, global::net.sf.jni4net.utils.Convertor.ParArrayPrimC2J(@__env, par0))));
            }
        }
        
        public int[] getAttributeIDs() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cint(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.@__ServiceRecord.j4n_getAttributeIDs4));
            }
        }
        
        public global::java.lang.String getConnectionURL(int par0, bool par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.@__ServiceRecord.j4n_getConnectionURL5, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1)));
            }
        }
        
        public global::javax.bluetooth.RemoteDevice getHostDevice() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.RemoteDevice>(@__env, @__env.CallObjectMethodPtr(this, global::javax.bluetooth.@__ServiceRecord.j4n_getHostDevice6));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ServiceRecord);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setDeviceServiceClasses", "setDeviceServiceClasses0", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAttributeValue", "setAttributeValue1", "(ILjavax/bluetooth/DataElement;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAttributeValue", "getAttributeValue2", "(I)Ljavax/bluetooth/DataElement;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "populateRecord", "populateRecord3", "([I)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getAttributeIDs", "getAttributeIDs4", "()[I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getConnectionURL", "getConnectionURL5", "(IZ)Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getHostDevice", "getHostDevice6", "()Ljavax/bluetooth/RemoteDevice;"));
            return methods;
        }
        
        private static void setDeviceServiceClasses0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int par0) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.bluetooth.ServiceRecord @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.ServiceRecord>(@__env, @__obj);
            @__real.setDeviceServiceClasses(par0);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool setAttributeValue1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (ILjavax/bluetooth/DataElement;)Z
            // (ILjavax/bluetooth/DataElement;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::javax.bluetooth.ServiceRecord @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.ServiceRecord>(@__env, @__obj);
            @__return = ((bool)(@__real.setAttributeValue(par0, global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.DataElement>(@__env, par1))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getAttributeValue2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int par0) {
            // (I)Ljavax/bluetooth/DataElement;
            // (I)Ljavax/bluetooth/DataElement;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.bluetooth.ServiceRecord @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.ServiceRecord>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getAttributeValue(par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool populateRecord3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // ([I)Z
            // ([I)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::javax.bluetooth.ServiceRecord @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.ServiceRecord>(@__env, @__obj);
            @__return = ((bool)(@__real.populateRecord(global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cint(@__env, par0))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getAttributeIDs4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[I
            // ()[I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.bluetooth.ServiceRecord @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.ServiceRecord>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getAttributeIDs());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getConnectionURL5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int par0, bool par1) {
            // (IZ)Ljava/lang/String;
            // (IZ)Ljava/lang/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.bluetooth.ServiceRecord @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.ServiceRecord>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getConnectionURL(par0, par1));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getHostDevice6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljavax/bluetooth/RemoteDevice;
            // ()Ljavax/bluetooth/RemoteDevice;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.bluetooth.ServiceRecord @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.ServiceRecord>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongCp2J(@__real.getHostDevice());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.bluetooth.@__ServiceRecord(@__env);
            }
        }
    }
    #endregion
}
