//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth.gcf.socket {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class SocketConnection : global::java.lang.Object, global::javax.microedition.io.SocketConnection {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_close0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_openDataInputStream1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_openInputStream2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_openDataOutputStream3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_openOutputStream4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getAddress5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getPort6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSocketOption7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setSocketOption8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getLocalAddress9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getLocalPort10;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DELAY11;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_LINGER12;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_KEEPALIVE13;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_RCVBUF14;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_SNDBUF15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSocketConnection16;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSocketConnection17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorSocketConnection18;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/net/Socket;)V")]
        public SocketConnection(global::java.lang.Object par0) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.NewObject(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n__ctorSocketConnection16, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;I)V")]
        public SocketConnection(global::java.lang.String par0, int par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n__ctorSocketConnection17, this, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public SocketConnection() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n__ctorSocketConnection18, this);
            }
        }
        
        protected SocketConnection(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("B")]
        public static byte DELAY {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((byte)(@__env.GetStaticByteField(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_DELAY11)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("B")]
        public static byte LINGER {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((byte)(@__env.GetStaticByteField(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_LINGER12)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("B")]
        public static byte KEEPALIVE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((byte)(@__env.GetStaticByteField(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_KEEPALIVE13)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("B")]
        public static byte RCVBUF {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((byte)(@__env.GetStaticByteField(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_RCVBUF14)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("B")]
        public static byte SNDBUF {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((byte)(@__env.GetStaticByteField(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_SNDBUF15)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass = @__class;
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_close0 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "close", "()V");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_openDataInputStream1 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "openDataInputStream", "()Ljava/io/DataInputStream;");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_openInputStream2 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "openInputStream", "()Ljava/io/InputStream;");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_openDataOutputStream3 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "openDataOutputStream", "()Ljava/io/DataOutputStream;");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_openOutputStream4 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "openOutputStream", "()Ljava/io/OutputStream;");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getAddress5 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "getAddress", "()Ljava/lang/String;");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getPort6 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "getPort", "()I");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getSocketOption7 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "getSocketOption", "(B)I");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_setSocketOption8 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "setSocketOption", "(BI)V");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getLocalAddress9 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "getLocalAddress", "()Ljava/lang/String;");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getLocalPort10 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "getLocalPort", "()I");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_DELAY11 = @__env.GetStaticFieldID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "DELAY", "B");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_LINGER12 = @__env.GetStaticFieldID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "LINGER", "B");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_KEEPALIVE13 = @__env.GetStaticFieldID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "KEEPALIVE", "B");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_RCVBUF14 = @__env.GetStaticFieldID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "RCVBUF", "B");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_SNDBUF15 = @__env.GetStaticFieldID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "SNDBUF", "B");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n__ctorSocketConnection16 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "<init>", "(Ljava/net/Socket;)V");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n__ctorSocketConnection17 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "<init>", "(Ljava/lang/String;I)V");
            global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n__ctorSocketConnection18 = @__env.GetMethodID(global::com.intel.bluetooth.gcf.socket.SocketConnection.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_close0);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/DataInputStream;")]
        public virtual global::java.io.InputStream openDataInputStream() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.InputStream>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_openDataInputStream1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/InputStream;")]
        public virtual global::java.io.InputStream openInputStream() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.InputStream>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_openInputStream2));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/DataOutputStream;")]
        public virtual global::java.io.FilterOutputStream openDataOutputStream() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.FilterOutputStream>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_openDataOutputStream3));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/io/OutputStream;")]
        public virtual global::java.io.OutputStream openOutputStream() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::java.io.OutputStream>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_openOutputStream4));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getAddress() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getAddress5));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getPort() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getPort6)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(B)I")]
        public virtual int getSocketOption(byte par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getSocketOption7, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(BI)V")]
        public virtual void setSocketOption(byte par0, int par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_setSocketOption8, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljava/lang/String;")]
        public virtual global::java.lang.String getLocalAddress() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getLocalAddress9));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getLocalPort() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::com.intel.bluetooth.gcf.socket.SocketConnection.j4n_getLocalPort10)));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.gcf.socket.SocketConnection(@__env);
            }
        }
    }
    #endregion
}
