//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth.obex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class OBEXClientSessionImpl : global::java.lang.Object, global::javax.obex.ClientSession, global::javax.microedition.io.Connection, global::com.intel.bluetooth.BluetoothConnectionAccess {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_close0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_get1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_put2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_connect3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_delete4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getConnectionID5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_createHeaderSet6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setPath7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setConnectionID8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setAuthenticator9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_disconnect10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_shutdown11;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_encrypt12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_isClosed13;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getRemoteAddress14;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getRemoteDevice15;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setRemoteDevice16;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getSecurityOpt17;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getBluetoothStack18;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_markAuthenticated19;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorOBEXClientSessionImpl20;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/microedition/io/StreamConnection;Lcom/intel/bluetooth/obex/OBEXConnection" +
            "Params;)V")]
        public OBEXClientSessionImpl(global::javax.microedition.io.StreamConnection par0, global::com.intel.bluetooth.obex.OBEXConnectionParams par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n__ctorOBEXClientSessionImpl20, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.microedition.io.StreamConnection>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1));
            }
        }
        
        protected OBEXClientSessionImpl(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass = @__class;
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_close0 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "close", "()V");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_get1 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "get", "(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_put2 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "put", "(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_connect3 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "connect", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_delete4 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "delete", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getConnectionID5 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "getConnectionID", "()J");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_createHeaderSet6 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "createHeaderSet", "()Ljavax/obex/HeaderSet;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_setPath7 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "setPath", "(Ljavax/obex/HeaderSet;ZZ)Ljavax/obex/HeaderSet;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_setConnectionID8 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "setConnectionID", "(J)V");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_setAuthenticator9 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "setAuthenticator", "(Ljavax/obex/Authenticator;)V");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_disconnect10 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "disconnect", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_shutdown11 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "shutdown", "()V");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_encrypt12 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "encrypt", "(JZ)Z");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_isClosed13 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "isClosed", "()Z");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getRemoteAddress14 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "getRemoteAddress", "()J");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getRemoteDevice15 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "getRemoteDevice", "()Ljavax/bluetooth/RemoteDevice;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_setRemoteDevice16 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "setRemoteDevice", "(Ljavax/bluetooth/RemoteDevice;)V");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getSecurityOpt17 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "getSecurityOpt", "()I");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getBluetoothStack18 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "getBluetoothStack", "()Lcom/intel/bluetooth/BluetoothStack;");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_markAuthenticated19 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "markAuthenticated", "()V");
            global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n__ctorOBEXClientSessionImpl20 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXClientSessionImpl.staticClass, "<init>", "(Ljavax/microedition/io/StreamConnection;Lcom/intel/bluetooth/obex/OBEXConnection" +
                    "Params;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_close0);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;")]
        public virtual global::javax.obex.Operation get(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.Operation>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_get1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;")]
        public virtual global::javax.obex.Operation put(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.Operation>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_put2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;")]
        public virtual global::javax.obex.HeaderSet connect(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_connect3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;")]
        public virtual global::javax.obex.HeaderSet delete(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_delete4, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        public virtual long getConnectionID() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getConnectionID5)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/obex/HeaderSet;")]
        public virtual global::javax.obex.HeaderSet createHeaderSet() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_createHeaderSet6));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;ZZ)Ljavax/obex/HeaderSet;")]
        public virtual global::javax.obex.HeaderSet setPath(global::javax.obex.HeaderSet par0, bool par1, bool par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_setPath7, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(J)V")]
        public virtual void setConnectionID(long par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_setConnectionID8, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/Authenticator;)V")]
        public virtual void setAuthenticator(global::javax.obex.Authenticator par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_setAuthenticator9, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.Authenticator>(@__env, par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;")]
        public virtual global::javax.obex.HeaderSet disconnect(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_disconnect10, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void shutdown() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_shutdown11);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(JZ)Z")]
        public virtual bool encrypt(long par0, bool par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_encrypt12, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool isClosed() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_isClosed13)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        public virtual long getRemoteAddress() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getRemoteAddress14)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/bluetooth/RemoteDevice;")]
        public virtual global::javax.bluetooth.RemoteDevice getRemoteDevice() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.bluetooth.RemoteDevice>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getRemoteDevice15));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/bluetooth/RemoteDevice;)V")]
        public virtual void setRemoteDevice(global::javax.bluetooth.RemoteDevice par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_setRemoteDevice16, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getSecurityOpt() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getSecurityOpt17)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Lcom/intel/bluetooth/BluetoothStack;")]
        public virtual global::com.intel.bluetooth.BluetoothStack getBluetoothStack() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::com.intel.bluetooth.BluetoothStack>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_getBluetoothStack18));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void markAuthenticated() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.obex.OBEXClientSessionImpl.j4n_markAuthenticated19);
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.obex.OBEXClientSessionImpl(@__env);
            }
        }
    }
    #endregion
}
