//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth.obex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class OBEXSessionNotifierImpl : global::java.lang.Object, global::javax.obex.SessionNotifier, global::com.intel.bluetooth.BluetoothConnectionNotifierServiceRecordAccess {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_close0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_acceptAndOpen1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_acceptAndOpen2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_updateServiceRecord3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getServiceRecord4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorOBEXSessionNotifierImpl5;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/microedition/io/StreamConnectionNotifier;Lcom/intel/bluetooth/obex/OBEXCo" +
            "nnectionParams;)V")]
        public OBEXSessionNotifierImpl(global::javax.microedition.io.StreamConnectionNotifier par0, global::com.intel.bluetooth.obex.OBEXConnectionParams par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass, global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n__ctorOBEXSessionNotifierImpl5, this, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.microedition.io.StreamConnectionNotifier>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par1));
            }
        }
        
        protected OBEXSessionNotifierImpl(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass = @__class;
            global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_close0 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass, "close", "()V");
            global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_acceptAndOpen1 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass, "acceptAndOpen", "(Ljavax/obex/ServerRequestHandler;)Ljavax/microedition/io/Connection;");
            global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_acceptAndOpen2 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass, "acceptAndOpen", "(Ljavax/obex/ServerRequestHandler;Ljavax/obex/Authenticator;)Ljavax/microedition/" +
                    "io/Connection;");
            global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_updateServiceRecord3 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass, "updateServiceRecord", "(Z)V");
            global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_getServiceRecord4 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass, "getServiceRecord", "()Ljavax/bluetooth/ServiceRecord;");
            global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n__ctorOBEXSessionNotifierImpl5 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.staticClass, "<init>", "(Ljavax/microedition/io/StreamConnectionNotifier;Lcom/intel/bluetooth/obex/OBEXCo" +
                    "nnectionParams;)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_close0);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/ServerRequestHandler;)Ljavax/microedition/io/Connection;")]
        public virtual global::javax.microedition.io.Connection acceptAndOpen(global::javax.obex.ServerRequestHandler par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.microedition.io.Connection>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_acceptAndOpen1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/ServerRequestHandler;Ljavax/obex/Authenticator;)Ljavax/microedition/" +
            "io/Connection;")]
        public virtual global::javax.microedition.io.Connection acceptAndOpen(global::javax.obex.ServerRequestHandler par0, global::javax.obex.Authenticator par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.microedition.io.Connection>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_acceptAndOpen2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.Authenticator>(@__env, par1)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Z)V")]
        public virtual void updateServiceRecord(bool par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_updateServiceRecord3, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/bluetooth/ServiceRecord;")]
        public virtual global::javax.bluetooth.ServiceRecord getServiceRecord() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.bluetooth.ServiceRecord>(@__env, @__env.CallObjectMethodPtr(this, global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl.j4n_getServiceRecord4));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.obex.OBEXSessionNotifierImpl(@__env);
            }
        }
    }
    #endregion
}
