//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.intel.bluetooth.obex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class OBEXConnectionParams : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DEFAULT_TIMEOUT0;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_OBEX_DEFAULT_MTU1;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_timeouts2;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_timeout3;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_mtu4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorOBEXConnectionParams5;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public OBEXConnectionParams() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n__ctorOBEXConnectionParams5, this);
            }
        }
        
        protected OBEXConnectionParams(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int DEFAULT_TIMEOUT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_DEFAULT_TIMEOUT0)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int OBEX_DEFAULT_MTU {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_OBEX_DEFAULT_MTU1)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("Z")]
        public virtual bool timeouts {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((bool)(@__env.GetBooleanField(this, global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_timeouts2)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public virtual int timeout {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetIntField(this, global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_timeout3)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public virtual int mtu {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetIntField(this, global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_mtu4)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass = @__class;
            global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_DEFAULT_TIMEOUT0 = @__env.GetStaticFieldID(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, "DEFAULT_TIMEOUT", "I");
            global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_OBEX_DEFAULT_MTU1 = @__env.GetStaticFieldID(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, "OBEX_DEFAULT_MTU", "I");
            global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_timeouts2 = @__env.GetFieldID(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, "timeouts", "Z");
            global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_timeout3 = @__env.GetFieldID(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, "timeout", "I");
            global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n_mtu4 = @__env.GetFieldID(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, "mtu", "I");
            global::com.intel.bluetooth.obex.OBEXConnectionParams.j4n__ctorOBEXConnectionParams5 = @__env.GetMethodID(global::com.intel.bluetooth.obex.OBEXConnectionParams.staticClass, "<init>", "()V");
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::com.intel.bluetooth.obex.OBEXConnectionParams(@__env);
            }
        }
    }
    #endregion
}
