//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controller {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class ControllerServer : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_openStream0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getMessage1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_closeConnection2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getMaster3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_addToWrite4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_startServer5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getplayerNames6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getplayerNames7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getDeviceNames8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_closeServer9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_checkMaster10;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getDeviceAdresses11;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_MAX_PLAYER12;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorControllerServer13;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public ControllerServer() : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.NewObject(global::Controller.ControllerServer.staticClass, global::Controller.ControllerServer.j4n__ctorControllerServer13, this);
            }
        }
        
        protected ControllerServer(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::Controller.ControllerServer.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int MAX_PLAYER {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::Controller.ControllerServer.staticClass, global::Controller.ControllerServer.j4n_MAX_PLAYER12)));
            }
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::Controller.ControllerServer.staticClass = @__class;
            global::Controller.ControllerServer.j4n_openStream0 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "openStream", "(I)V");
            global::Controller.ControllerServer.j4n_getMessage1 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "getMessage", "(I)Ljava/lang/String;");
            global::Controller.ControllerServer.j4n_closeConnection2 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "closeConnection", "(I)V");
            global::Controller.ControllerServer.j4n_getMaster3 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "getMaster", "()I");
            global::Controller.ControllerServer.j4n_addToWrite4 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "addToWrite", "(Ljava/lang/String;I)V");
            global::Controller.ControllerServer.j4n_startServer5 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "startServer", "()Z");
            global::Controller.ControllerServer.j4n_getplayerNames6 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "getplayerNames", "(I)Ljava/lang/String;");
            global::Controller.ControllerServer.j4n_getplayerNames7 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "getplayerNames", "()[Ljava/lang/String;");
            global::Controller.ControllerServer.j4n_getDeviceNames8 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "getDeviceNames", "()[Ljava/lang/String;");
            global::Controller.ControllerServer.j4n_closeServer9 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "closeServer", "()V");
            global::Controller.ControllerServer.j4n_checkMaster10 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "checkMaster", "()V");
            global::Controller.ControllerServer.j4n_getDeviceAdresses11 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "getDeviceAdresses", "()[Ljava/lang/String;");
            global::Controller.ControllerServer.j4n_MAX_PLAYER12 = @__env.GetStaticFieldID(global::Controller.ControllerServer.staticClass, "MAX_PLAYER", "I");
            global::Controller.ControllerServer.j4n__ctorControllerServer13 = @__env.GetMethodID(global::Controller.ControllerServer.staticClass, "<init>", "()V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)V")]
        public virtual void openStream(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::Controller.ControllerServer.j4n_openStream0, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)Ljava/lang/String;")]
        public virtual global::java.lang.String getMessage(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::Controller.ControllerServer.j4n_getMessage1, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)V")]
        public virtual void closeConnection(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::Controller.ControllerServer.j4n_closeConnection2, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        public virtual int getMaster() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::Controller.ControllerServer.j4n_getMaster3)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;I)V")]
        public virtual void addToWrite(global::java.lang.String par0, int par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::Controller.ControllerServer.j4n_addToWrite4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Z")]
        public virtual bool startServer() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((bool)(@__env.CallBooleanMethod(this, global::Controller.ControllerServer.j4n_startServer5)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)Ljava/lang/String;")]
        public virtual global::java.lang.String getplayerNames(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::Controller.ControllerServer.j4n_getplayerNames6, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Ljava/lang/String;")]
        public virtual global::java.lang.String[] getplayerNames() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::Controller.ControllerServer.j4n_getplayerNames7));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Ljava/lang/String;")]
        public virtual global::java.lang.String[] getDeviceNames() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::Controller.ControllerServer.j4n_getDeviceNames8));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void closeServer() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::Controller.ControllerServer.j4n_closeServer9);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()V")]
        public virtual void checkMaster() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::Controller.ControllerServer.j4n_checkMaster10);
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[Ljava/lang/String;")]
        public virtual global::java.lang.String[] getDeviceAdresses() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayStrongJ2CpString(@__env, @__env.CallObjectMethodPtr(this, global::Controller.ControllerServer.j4n_getDeviceAdresses11));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::Controller.ControllerServer(@__env);
            }
        }
    }
    #endregion
}
