//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.obex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface ClientSession : global::javax.microedition.io.Connection {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;")]
        global::javax.obex.Operation get(global::javax.obex.HeaderSet par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;")]
        global::javax.obex.Operation put(global::javax.obex.HeaderSet par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;")]
        global::javax.obex.HeaderSet connect(global::javax.obex.HeaderSet par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;")]
        global::javax.obex.HeaderSet delete(global::javax.obex.HeaderSet par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        long getConnectionID();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/obex/HeaderSet;")]
        global::javax.obex.HeaderSet createHeaderSet();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;ZZ)Ljavax/obex/HeaderSet;")]
        global::javax.obex.HeaderSet setPath(global::javax.obex.HeaderSet par0, bool par1, bool par2);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(J)V")]
        void setConnectionID(long par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/Authenticator;)V")]
        void setAuthenticator(global::javax.obex.Authenticator par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;")]
        global::javax.obex.HeaderSet disconnect(global::javax.obex.HeaderSet par0);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class ClientSession_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.obex.@__ClientSession.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::javax.obex.ClientSession), typeof(global::javax.obex.ClientSession_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::javax.obex.ClientSession), typeof(global::javax.obex.ClientSession_))]
    internal sealed partial class @__ClientSession : global::java.lang.Object, global::javax.obex.ClientSession {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_close0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_get1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_put2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_connect3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_delete4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getConnectionID5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_createHeaderSet6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setPath7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setConnectionID8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setAuthenticator9;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_disconnect10;
        
        private @__ClientSession(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.obex.@__ClientSession.staticClass = @__class;
            global::javax.obex.@__ClientSession.j4n_close0 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "close", "()V");
            global::javax.obex.@__ClientSession.j4n_get1 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "get", "(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;");
            global::javax.obex.@__ClientSession.j4n_put2 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "put", "(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;");
            global::javax.obex.@__ClientSession.j4n_connect3 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "connect", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;");
            global::javax.obex.@__ClientSession.j4n_delete4 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "delete", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;");
            global::javax.obex.@__ClientSession.j4n_getConnectionID5 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "getConnectionID", "()J");
            global::javax.obex.@__ClientSession.j4n_createHeaderSet6 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "createHeaderSet", "()Ljavax/obex/HeaderSet;");
            global::javax.obex.@__ClientSession.j4n_setPath7 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "setPath", "(Ljavax/obex/HeaderSet;ZZ)Ljavax/obex/HeaderSet;");
            global::javax.obex.@__ClientSession.j4n_setConnectionID8 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "setConnectionID", "(J)V");
            global::javax.obex.@__ClientSession.j4n_setAuthenticator9 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "setAuthenticator", "(Ljavax/obex/Authenticator;)V");
            global::javax.obex.@__ClientSession.j4n_disconnect10 = @__env.GetMethodID(global::javax.obex.@__ClientSession.staticClass, "disconnect", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;");
        }
        
        public void close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::javax.obex.@__ClientSession.j4n_close0);
            }
        }
        
        public global::javax.obex.Operation get(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.Operation>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__ClientSession.j4n_get1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        public global::javax.obex.Operation put(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.Operation>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__ClientSession.j4n_put2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        public global::javax.obex.HeaderSet connect(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__ClientSession.j4n_connect3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        public global::javax.obex.HeaderSet delete(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__ClientSession.j4n_delete4, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        public long getConnectionID() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::javax.obex.@__ClientSession.j4n_getConnectionID5)));
            }
        }
        
        public global::javax.obex.HeaderSet createHeaderSet() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__ClientSession.j4n_createHeaderSet6));
            }
        }
        
        public global::javax.obex.HeaderSet setPath(global::javax.obex.HeaderSet par0, bool par1, bool par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__ClientSession.j4n_setPath7, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2)));
            }
        }
        
        public void setConnectionID(long par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::javax.obex.@__ClientSession.j4n_setConnectionID8, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        public void setAuthenticator(global::javax.obex.Authenticator par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::javax.obex.@__ClientSession.j4n_setAuthenticator9, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.Authenticator>(@__env, par0));
            }
        }
        
        public global::javax.obex.HeaderSet disconnect(global::javax.obex.HeaderSet par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__ClientSession.j4n_disconnect10, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ClientSession);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "close", "close0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "get", "get1", "(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "put", "put2", "(Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "connect", "connect3", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "delete", "delete4", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getConnectionID", "getConnectionID5", "()J"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "createHeaderSet", "createHeaderSet6", "()Ljavax/obex/HeaderSet;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setPath", "setPath7", "(Ljavax/obex/HeaderSet;ZZ)Ljavax/obex/HeaderSet;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setConnectionID", "setConnectionID8", "(J)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setAuthenticator", "setAuthenticator9", "(Ljavax/obex/Authenticator;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "disconnect", "disconnect10", "(Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;"));
            return methods;
        }
        
        private static void close0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            ((global::javax.microedition.io.Connection)(@__real)).close();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle get1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.obex.Operation>(@__env, @__real.get(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle put2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/Operation;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.obex.Operation>(@__env, @__real.put(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle connect3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.obex.HeaderSet>(@__env, @__real.connect(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle delete4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.obex.HeaderSet>(@__env, @__real.delete(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static long getConnectionID5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()J
            // ()J
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            long @__return = default(long);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__return = ((long)(@__real.getConnectionID()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle createHeaderSet6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljavax/obex/HeaderSet;
            // ()Ljavax/obex/HeaderSet;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.obex.HeaderSet>(@__env, @__real.createHeaderSet());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle setPath7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, bool par1, bool par2) {
            // (Ljavax/obex/HeaderSet;ZZ)Ljavax/obex/HeaderSet;
            // (Ljavax/obex/HeaderSet;ZZ)Ljavax/obex/HeaderSet;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.obex.HeaderSet>(@__env, @__real.setPath(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, par0), par1, par2));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setConnectionID8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, long par0) {
            // (J)V
            // (J)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__real.setConnectionID(par0);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void setAuthenticator9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljavax/obex/Authenticator;)V
            // (Ljavax/obex/Authenticator;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__real.setAuthenticator(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.Authenticator>(@__env, par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle disconnect10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;
            // (Ljavax/obex/HeaderSet;)Ljavax/obex/HeaderSet;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.ClientSession @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.ClientSession>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.obex.HeaderSet>(@__env, @__real.disconnect(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.obex.@__ClientSession(@__env);
            }
        }
    }
    #endregion
}
