//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.obex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface HeaderSet {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()I")]
        int getResponseCode();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(I)Ljava/lang/Object;")]
        global::java.lang.Object getHeader(int par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[I")]
        int[] getHeaderList();
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(ILjava/lang/Object;)V")]
        void setHeader(int par0, global::java.lang.Object par1);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljava/lang/String;ZZ)V")]
        void createAuthenticationChallenge(global::java.lang.String par0, bool par1, bool par2);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class HeaderSet_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.obex.@__HeaderSet.staticClass;
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int COUNT {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_COUNT5)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int NAME {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_NAME6)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int TYPE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_TYPE7)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int LENGTH {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_LENGTH8)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int TIME_ISO_8601 {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_TIME_ISO_86019)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int TIME_4_BYTE {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_TIME_4_BYTE10)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int DESCRIPTION {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_DESCRIPTION11)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int TARGET {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_TARGET12)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int HTTP {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_HTTP13)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int WHO {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_WHO14)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int OBJECT_CLASS {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_OBJECT_CLASS15)));
            }
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("I")]
        public static int APPLICATION_PARAMETER {
            get {
                global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
                return ((int)(@__env.GetStaticIntField(global::javax.obex.@__HeaderSet.staticClass, global::javax.obex.@__HeaderSet.j4n_APPLICATION_PARAMETER16)));
            }
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::javax.obex.HeaderSet), typeof(global::javax.obex.HeaderSet_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::javax.obex.HeaderSet), typeof(global::javax.obex.HeaderSet_))]
    internal sealed partial class @__HeaderSet : global::java.lang.Object, global::javax.obex.HeaderSet {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getResponseCode0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getHeader1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getHeaderList2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setHeader3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_createAuthenticationChallenge4;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_COUNT5;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_NAME6;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_TYPE7;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_LENGTH8;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_TIME_ISO_86019;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_TIME_4_BYTE10;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_DESCRIPTION11;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_TARGET12;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_HTTP13;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_WHO14;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_OBJECT_CLASS15;
        
        internal static global::net.sf.jni4net.jni.FieldId j4n_APPLICATION_PARAMETER16;
        
        private @__HeaderSet(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.obex.@__HeaderSet.staticClass = @__class;
            global::javax.obex.@__HeaderSet.j4n_getResponseCode0 = @__env.GetMethodID(global::javax.obex.@__HeaderSet.staticClass, "getResponseCode", "()I");
            global::javax.obex.@__HeaderSet.j4n_getHeader1 = @__env.GetMethodID(global::javax.obex.@__HeaderSet.staticClass, "getHeader", "(I)Ljava/lang/Object;");
            global::javax.obex.@__HeaderSet.j4n_getHeaderList2 = @__env.GetMethodID(global::javax.obex.@__HeaderSet.staticClass, "getHeaderList", "()[I");
            global::javax.obex.@__HeaderSet.j4n_setHeader3 = @__env.GetMethodID(global::javax.obex.@__HeaderSet.staticClass, "setHeader", "(ILjava/lang/Object;)V");
            global::javax.obex.@__HeaderSet.j4n_createAuthenticationChallenge4 = @__env.GetMethodID(global::javax.obex.@__HeaderSet.staticClass, "createAuthenticationChallenge", "(Ljava/lang/String;ZZ)V");
            global::javax.obex.@__HeaderSet.j4n_COUNT5 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "COUNT", "I");
            global::javax.obex.@__HeaderSet.j4n_NAME6 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "NAME", "I");
            global::javax.obex.@__HeaderSet.j4n_TYPE7 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "TYPE", "I");
            global::javax.obex.@__HeaderSet.j4n_LENGTH8 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "LENGTH", "I");
            global::javax.obex.@__HeaderSet.j4n_TIME_ISO_86019 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "TIME_ISO_8601", "I");
            global::javax.obex.@__HeaderSet.j4n_TIME_4_BYTE10 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "TIME_4_BYTE", "I");
            global::javax.obex.@__HeaderSet.j4n_DESCRIPTION11 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "DESCRIPTION", "I");
            global::javax.obex.@__HeaderSet.j4n_TARGET12 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "TARGET", "I");
            global::javax.obex.@__HeaderSet.j4n_HTTP13 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "HTTP", "I");
            global::javax.obex.@__HeaderSet.j4n_WHO14 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "WHO", "I");
            global::javax.obex.@__HeaderSet.j4n_OBJECT_CLASS15 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "OBJECT_CLASS", "I");
            global::javax.obex.@__HeaderSet.j4n_APPLICATION_PARAMETER16 = @__env.GetStaticFieldID(global::javax.obex.@__HeaderSet.staticClass, "APPLICATION_PARAMETER", "I");
        }
        
        public int getResponseCode() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((int)(@__env.CallIntMethod(this, global::javax.obex.@__HeaderSet.j4n_getResponseCode0)));
            }
        }
        
        public global::java.lang.Object getHeader(int par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__HeaderSet.j4n_getHeader1, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0)));
            }
        }
        
        public int[] getHeaderList() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cint(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__HeaderSet.j4n_getHeaderList2));
            }
        }
        
        public void setHeader(int par0, global::java.lang.Object par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::javax.obex.@__HeaderSet.j4n_setHeader3, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::java.lang.Object>(@__env, par1));
            }
        }
        
        public void createAuthenticationChallenge(global::java.lang.String par0, bool par1, bool par2) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 16)){
            @__env.CallVoidMethod(this, global::javax.obex.@__HeaderSet.j4n_createAuthenticationChallenge4, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__HeaderSet);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getResponseCode", "getResponseCode0", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getHeader", "getHeader1", "(I)Ljava/lang/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getHeaderList", "getHeaderList2", "()[I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setHeader", "setHeader3", "(ILjava/lang/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "createAuthenticationChallenge", "createAuthenticationChallenge4", "(Ljava/lang/String;ZZ)V"));
            return methods;
        }
        
        private static int getResponseCode0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::javax.obex.HeaderSet @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__obj);
            @__return = ((int)(@__real.getResponseCode()));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getHeader1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int par0) {
            // (I)Ljava/lang/Object;
            // (I)Ljava/lang/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.HeaderSet @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::java.lang.Object>(@__env, @__real.getHeader(par0));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle getHeaderList2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[I
            // ()[I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.HeaderSet @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayPrimC2J(@__env, @__real.getHeaderList());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void setHeader3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (ILjava/lang/Object;)V
            // (ILjava/lang/Object;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.obex.HeaderSet @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__obj);
            @__real.setHeader(par0, global::net.sf.jni4net.utils.Convertor.FullJ2C<global::java.lang.Object>(@__env, par1));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void createAuthenticationChallenge4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, bool par1, bool par2) {
            // (Ljava/lang/String;ZZ)V
            // (Ljava/lang/String;ZZ)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.obex.HeaderSet @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__obj);
            @__real.createAuthenticationChallenge(global::net.sf.jni4net.utils.Convertor.StrongJ2CpString(@__env, par0), par1, par2);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.obex.@__HeaderSet(@__env);
            }
        }
    }
    #endregion
}
