//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.obex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class PasswordAuthentication : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getUserName0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getPassword1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n__ctorPasswordAuthentication2;
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([B[B)V")]
        public PasswordAuthentication(byte[] par0, byte[] par1) : 
                base(((global::net.sf.jni4net.jni.JNIEnv)(null))) {
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.ThreadEnv;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.NewObject(global::javax.obex.PasswordAuthentication.staticClass, global::javax.obex.PasswordAuthentication.j4n__ctorPasswordAuthentication2, this, global::net.sf.jni4net.utils.Convertor.ParArrayPrimC2J(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParArrayPrimC2J(@__env, par1));
            }
        }
        
        protected PasswordAuthentication(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.obex.PasswordAuthentication.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.obex.PasswordAuthentication.staticClass = @__class;
            global::javax.obex.PasswordAuthentication.j4n_getUserName0 = @__env.GetMethodID(global::javax.obex.PasswordAuthentication.staticClass, "getUserName", "()[B");
            global::javax.obex.PasswordAuthentication.j4n_getPassword1 = @__env.GetMethodID(global::javax.obex.PasswordAuthentication.staticClass, "getPassword", "()[B");
            global::javax.obex.PasswordAuthentication.j4n__ctorPasswordAuthentication2 = @__env.GetMethodID(global::javax.obex.PasswordAuthentication.staticClass, "<init>", "([B[B)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[B")]
        public virtual byte[] getUserName() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cbyte(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.PasswordAuthentication.j4n_getUserName0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()[B")]
        public virtual byte[] getPassword() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.ArrayPrimJ2Cbyte(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.PasswordAuthentication.j4n_getPassword1));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.obex.PasswordAuthentication(@__env);
            }
        }
    }
    #endregion
}
