//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.obex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaClassAttribute()]
    public partial class ServerRequestHandler : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onConnect0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onDisconnect1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onDelete2;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onPut3;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onGet4;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_getConnectionID5;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_createHeaderSet6;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_setConnectionID7;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onSetPath8;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_onAuthenticationFailure9;
        
        protected ServerRequestHandler(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.obex.ServerRequestHandler.staticClass;
            }
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.obex.ServerRequestHandler.staticClass = @__class;
            global::javax.obex.ServerRequestHandler.j4n_onConnect0 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "onConnect", "(Ljavax/obex/HeaderSet;Ljavax/obex/HeaderSet;)I");
            global::javax.obex.ServerRequestHandler.j4n_onDisconnect1 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "onDisconnect", "(Ljavax/obex/HeaderSet;Ljavax/obex/HeaderSet;)V");
            global::javax.obex.ServerRequestHandler.j4n_onDelete2 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "onDelete", "(Ljavax/obex/HeaderSet;Ljavax/obex/HeaderSet;)I");
            global::javax.obex.ServerRequestHandler.j4n_onPut3 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "onPut", "(Ljavax/obex/Operation;)I");
            global::javax.obex.ServerRequestHandler.j4n_onGet4 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "onGet", "(Ljavax/obex/Operation;)I");
            global::javax.obex.ServerRequestHandler.j4n_getConnectionID5 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "getConnectionID", "()J");
            global::javax.obex.ServerRequestHandler.j4n_createHeaderSet6 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "createHeaderSet", "()Ljavax/obex/HeaderSet;");
            global::javax.obex.ServerRequestHandler.j4n_setConnectionID7 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "setConnectionID", "(J)V");
            global::javax.obex.ServerRequestHandler.j4n_onSetPath8 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "onSetPath", "(Ljavax/obex/HeaderSet;Ljavax/obex/HeaderSet;ZZ)I");
            global::javax.obex.ServerRequestHandler.j4n_onAuthenticationFailure9 = @__env.GetMethodID(global::javax.obex.ServerRequestHandler.staticClass, "onAuthenticationFailure", "([B)V");
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;Ljavax/obex/HeaderSet;)I")]
        public virtual int onConnect(global::javax.obex.HeaderSet par0, global::javax.obex.HeaderSet par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((int)(@__env.CallIntMethod(this, global::javax.obex.ServerRequestHandler.j4n_onConnect0, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par1))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;Ljavax/obex/HeaderSet;)V")]
        public virtual void onDisconnect(global::javax.obex.HeaderSet par0, global::javax.obex.HeaderSet par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            @__env.CallVoidMethod(this, global::javax.obex.ServerRequestHandler.j4n_onDisconnect1, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par1));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;Ljavax/obex/HeaderSet;)I")]
        public virtual int onDelete(global::javax.obex.HeaderSet par0, global::javax.obex.HeaderSet par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return ((int)(@__env.CallIntMethod(this, global::javax.obex.ServerRequestHandler.j4n_onDelete2, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par1))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/Operation;)I")]
        public virtual int onPut(global::javax.obex.Operation par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::javax.obex.ServerRequestHandler.j4n_onPut3, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.Operation>(@__env, par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/Operation;)I")]
        public virtual int onGet(global::javax.obex.Operation par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return ((int)(@__env.CallIntMethod(this, global::javax.obex.ServerRequestHandler.j4n_onGet4, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.Operation>(@__env, par0))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()J")]
        public virtual long getConnectionID() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return ((long)(@__env.CallLongMethod(this, global::javax.obex.ServerRequestHandler.j4n_getConnectionID5)));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("()Ljavax/obex/HeaderSet;")]
        public global::javax.obex.HeaderSet createHeaderSet() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.HeaderSet>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.ServerRequestHandler.j4n_createHeaderSet6));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(J)V")]
        public virtual void setConnectionID(long par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::javax.obex.ServerRequestHandler.j4n_setConnectionID7, global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par0));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/HeaderSet;Ljavax/obex/HeaderSet;ZZ)I")]
        public virtual int onSetPath(global::javax.obex.HeaderSet par0, global::javax.obex.HeaderSet par1, bool par2, bool par3) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 18)){
            return ((int)(@__env.CallIntMethod(this, global::javax.obex.ServerRequestHandler.j4n_onSetPath8, global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.HeaderSet>(@__env, par1), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par2), global::net.sf.jni4net.utils.Convertor.ParPrimC2J(par3))));
            }
        }
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("([B)V")]
        public virtual void onAuthenticationFailure(byte[] par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            @__env.CallVoidMethod(this, global::javax.obex.ServerRequestHandler.j4n_onAuthenticationFailure9, global::net.sf.jni4net.utils.Convertor.ParArrayPrimC2J(@__env, par0));
            }
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.obex.ServerRequestHandler(@__env);
            }
        }
    }
    #endregion
}
