//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace javax.obex {
    
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaInterfaceAttribute()]
    public partial interface SessionNotifier : global::javax.microedition.io.Connection {
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/ServerRequestHandler;)Ljavax/microedition/io/Connection;")]
        global::javax.microedition.io.Connection acceptAndOpen(global::javax.obex.ServerRequestHandler par0);
        
        [global::net.sf.jni4net.attributes.JavaMethodAttribute("(Ljavax/obex/ServerRequestHandler;Ljavax/obex/Authenticator;)Ljavax/microedition/" +
            "io/Connection;")]
        global::javax.microedition.io.Connection acceptAndOpen(global::javax.obex.ServerRequestHandler par0, global::javax.obex.Authenticator par1);
    }
    #endregion
    
    #region Component Designer generated code 
    public partial class SessionNotifier_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::javax.obex.@__SessionNotifier.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::javax.obex.SessionNotifier), typeof(global::javax.obex.SessionNotifier_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::javax.obex.SessionNotifier), typeof(global::javax.obex.SessionNotifier_))]
    internal sealed partial class @__SessionNotifier : global::java.lang.Object, global::javax.obex.SessionNotifier {
        
        internal new static global::java.lang.Class staticClass;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_close0;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_acceptAndOpen1;
        
        internal static global::net.sf.jni4net.jni.MethodId j4n_acceptAndOpen2;
        
        private @__SessionNotifier(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::javax.obex.@__SessionNotifier.staticClass = @__class;
            global::javax.obex.@__SessionNotifier.j4n_close0 = @__env.GetMethodID(global::javax.obex.@__SessionNotifier.staticClass, "close", "()V");
            global::javax.obex.@__SessionNotifier.j4n_acceptAndOpen1 = @__env.GetMethodID(global::javax.obex.@__SessionNotifier.staticClass, "acceptAndOpen", "(Ljavax/obex/ServerRequestHandler;)Ljavax/microedition/io/Connection;");
            global::javax.obex.@__SessionNotifier.j4n_acceptAndOpen2 = @__env.GetMethodID(global::javax.obex.@__SessionNotifier.staticClass, "acceptAndOpen", "(Ljavax/obex/ServerRequestHandler;Ljavax/obex/Authenticator;)Ljavax/microedition/" +
                    "io/Connection;");
        }
        
        public void close() {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 10)){
            @__env.CallVoidMethod(this, global::javax.obex.@__SessionNotifier.j4n_close0);
            }
        }
        
        public global::javax.microedition.io.Connection acceptAndOpen(global::javax.obex.ServerRequestHandler par0) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 12)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.microedition.io.Connection>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__SessionNotifier.j4n_acceptAndOpen1, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0)));
            }
        }
        
        public global::javax.microedition.io.Connection acceptAndOpen(global::javax.obex.ServerRequestHandler par0, global::javax.obex.Authenticator par1) {
            global::net.sf.jni4net.jni.JNIEnv @__env = this.Env;
            using(new global::net.sf.jni4net.jni.LocalFrame(@__env, 14)){
            return global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.microedition.io.Connection>(@__env, @__env.CallObjectMethodPtr(this, global::javax.obex.@__SessionNotifier.j4n_acceptAndOpen2, global::net.sf.jni4net.utils.Convertor.ParStrongCp2J(par0), global::net.sf.jni4net.utils.Convertor.ParFullC2J<global::javax.obex.Authenticator>(@__env, par1)));
            }
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__SessionNotifier);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "close", "close0", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "acceptAndOpen", "acceptAndOpen1", "(Ljavax/obex/ServerRequestHandler;)Ljavax/microedition/io/Connection;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "acceptAndOpen", "acceptAndOpen2", "(Ljavax/obex/ServerRequestHandler;Ljavax/obex/Authenticator;)Ljavax/microedition/" +
                        "io/Connection;"));
            return methods;
        }
        
        private static void close0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::javax.obex.SessionNotifier @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.SessionNotifier>(@__env, @__obj);
            ((global::javax.microedition.io.Connection)(@__real)).close();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle acceptAndOpen1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0) {
            // (Ljavax/obex/ServerRequestHandler;)Ljavax/microedition/io/Connection;
            // (Ljavax/obex/ServerRequestHandler;)Ljavax/microedition/io/Connection;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.SessionNotifier @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.SessionNotifier>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.microedition.io.Connection>(@__env, @__real.acceptAndOpen(global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.obex.ServerRequestHandler>(@__env, par0)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle acceptAndOpen2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle par0, global::net.sf.jni4net.utils.JniLocalHandle par1) {
            // (Ljavax/obex/ServerRequestHandler;Ljavax/obex/Authenticator;)Ljavax/microedition/io/Connection;
            // (Ljavax/obex/ServerRequestHandler;Ljavax/obex/Authenticator;)Ljavax/microedition/io/Connection;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::javax.obex.SessionNotifier @__real = global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.SessionNotifier>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::javax.microedition.io.Connection>(@__env, @__real.acceptAndOpen(global::net.sf.jni4net.utils.Convertor.StrongJ2Cp<global::javax.obex.ServerRequestHandler>(@__env, par0), global::net.sf.jni4net.utils.Convertor.FullJ2C<global::javax.obex.Authenticator>(@__env, par1)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::javax.obex.@__SessionNotifier(@__env);
            }
        }
    }
    #endregion
}
